package dao

import (
	"context"
	"errors"
	"fmt"
	"os"
	"sync"
	"testing"
	"time"

	"github.com/jackc/pgx/v5/pgxpool"
	"github.com/teamgram/proto/mtproto"
)

func TestEncryptedFileMetadataPostgres18RoundTrip(t *testing.T) {
	dsn := os.Getenv("TEAMGRAM_POSTGRES_DSN")
	if dsn == "" {
		t.Skip("TEAMGRAM_POSTGRES_DSN must point to an isolated PostgreSQL 18 database")
	}
	ctx, cancel := context.WithTimeout(context.Background(), 15*time.Second)
	defer cancel()
	admin, err := pgxpool.New(ctx, dsn)
	if err != nil {
		t.Fatal(err)
	}
	t.Cleanup(admin.Close)
	var version int
	if err := admin.QueryRow(ctx, `SELECT current_setting('server_version_num')::integer`).Scan(&version); err != nil {
		t.Fatal(err)
	}
	if version/10000 != 18 {
		t.Skipf("PostgreSQL 18 required, connected to server_version_num=%d", version)
	}
	schema := fmt.Sprintf("encrypted_file_test_%d", time.Now().UnixNano())
	if _, err := admin.Exec(ctx, `CREATE SCHEMA `+schema); err != nil {
		t.Fatal(err)
	}
	t.Cleanup(func() { _, _ = admin.Exec(context.Background(), `DROP SCHEMA `+schema+` CASCADE`) })
	config, err := pgxpool.ParseConfig(dsn)
	if err != nil {
		t.Fatal(err)
	}
	config.ConnConfig.RuntimeParams["search_path"] = schema
	pool, err := pgxpool.NewWithConfig(ctx, config)
	if err != nil {
		t.Fatal(err)
	}
	t.Cleanup(pool.Close)
	_, err = pool.Exec(ctx, `CREATE TABLE encrypted_files (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 encrypted_file_id BIGINT NOT NULL UNIQUE,
 owner_id BIGINT NOT NULL,
 access_hash BIGINT NOT NULL,
 file_size BIGINT NOT NULL,
 dc_id INTEGER NOT NULL,
 key_fingerprint INTEGER NOT NULL DEFAULT 0,
 created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
)`)
	if err != nil {
		t.Fatal(err)
	}
	store := &Postgres{Pool: pool}
	want := mtproto.MakeTLEncryptedFile(&mtproto.EncryptedFile{
		Id: 901, AccessHash: 902, Size2_INT64: 4097, Size2_INT32: 4097, DcId: 2, KeyFingerprint: 77,
	}).To_EncryptedFile()
	if err := store.SaveEncryptedFile(ctx, 17, want); err != nil {
		t.Fatalf("save: %v", err)
	}
	if err := store.SaveEncryptedFile(ctx, 17, want); err != nil {
		t.Fatalf("idempotent save: %v", err)
	}
	concurrent := mtproto.MakeTLEncryptedFile(&mtproto.EncryptedFile{
		Id: 903, AccessHash: 904, Size2_INT64: 2048, Size2_INT32: 2048, DcId: 2, KeyFingerprint: 78,
	}).To_EncryptedFile()
	var wg sync.WaitGroup
	errs := make(chan error, 8)
	for i := 0; i < 8; i++ {
		wg.Add(1)
		go func() {
			defer wg.Done()
			errs <- store.SaveEncryptedFile(ctx, -17, concurrent)
		}()
	}
	wg.Wait()
	close(errs)
	for err := range errs {
		if err != nil {
			t.Fatalf("concurrent save: %v", err)
		}
	}
	var rows int
	if err := pool.QueryRow(ctx, `SELECT count(*) FROM encrypted_files WHERE encrypted_file_id = $1`, concurrent.GetId()).Scan(&rows); err != nil || rows != 1 {
		t.Fatalf("concurrent row count = %d, err = %v", rows, err)
	}
	got, err := store.GetEncryptedFile(ctx, want.GetId(), want.GetAccessHash())
	if err != nil {
		t.Fatalf("get: %v", err)
	}
	if got.GetId() != want.GetId() || got.GetAccessHash() != want.GetAccessHash() || got.GetSize2_INT64() != want.GetSize2_INT64() || got.GetKeyFingerprint() != want.GetKeyFingerprint() {
		t.Fatalf("round trip = %v, want %v", got, want)
	}
	if _, err := store.GetEncryptedFile(ctx, want.GetId(), want.GetAccessHash()+1); !errors.Is(err, mtproto.ErrFileIdInvalid) {
		t.Fatalf("wrong access hash error = %v", err)
	}
	conflict := mtproto.MakeTLEncryptedFile(&mtproto.EncryptedFile{
		Id: want.GetId(), AccessHash: want.GetAccessHash() + 1, Size2_INT64: want.GetSize2_INT64(), Size2_INT32: want.GetSize2_INT32(), DcId: want.GetDcId(), KeyFingerprint: want.GetKeyFingerprint(),
	}).To_EncryptedFile()
	if err := store.SaveEncryptedFile(ctx, 17, conflict); !errors.Is(err, mtproto.ErrFileIdInvalid) {
		t.Fatalf("conflicting encrypted file identity error = %v", err)
	}
}
