package dao

import (
	"context"
	"fmt"
	"os"
	"testing"
	"time"

	"github.com/jackc/pgx/v5/pgxpool"
	"github.com/teamgram/proto/mtproto"
	"github.com/teamgram/teamgram-server/app/service/media/internal/dal/dao/postgres_dao"
)

func TestSavePhotoAggregateV2Postgres18Atomicity(t *testing.T) {
	dsn := os.Getenv("TEAMGRAM_POSTGRES_DSN")
	if dsn == "" {
		t.Skip("TEAMGRAM_POSTGRES_DSN must point to a PostgreSQL 18 test database")
	}
	ctx, cancel := context.WithTimeout(context.Background(), 15*time.Second)
	defer cancel()

	admin, err := pgxpool.New(ctx, dsn)
	if err != nil {
		t.Fatalf("open PostgreSQL test database: %v", err)
	}
	t.Cleanup(admin.Close)
	var serverVersion int
	if err := admin.QueryRow(ctx, `SELECT current_setting('server_version_num')::integer`).Scan(&serverVersion); err != nil {
		t.Fatal(err)
	}
	if serverVersion/10000 != 18 {
		t.Skipf("PostgreSQL 18 required, connected to server_version_num=%d", serverVersion)
	}

	schema := fmt.Sprintf("media_photo_test_%d", time.Now().UnixNano())
	if _, err := admin.Exec(ctx, `CREATE SCHEMA `+schema); err != nil {
		t.Fatal(err)
	}
	poolConfig, err := pgxpool.ParseConfig(dsn)
	if err != nil {
		t.Fatal(err)
	}
	poolConfig.ConnConfig.RuntimeParams["search_path"] = schema
	pool, err := pgxpool.NewWithConfig(ctx, poolConfig)
	if err != nil {
		_, _ = admin.Exec(context.Background(), `DROP SCHEMA `+schema+` CASCADE`)
		t.Fatal(err)
	}
	t.Cleanup(func() {
		pool.Close()
		_, _ = admin.Exec(context.Background(), `DROP SCHEMA `+schema+` CASCADE`)
	})
	if err := pool.Ping(ctx); err != nil {
		t.Fatal(err)
	}
	_, err = pool.Exec(ctx, `CREATE TABLE photos (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 photo_id BIGINT NOT NULL UNIQUE,
 access_hash BIGINT NOT NULL,
 has_stickers BOOLEAN NOT NULL,
 dc_id INTEGER NOT NULL,
 date2 BIGINT NOT NULL,
 has_video BOOLEAN NOT NULL,
 size_id BIGINT NOT NULL,
 video_size_id BIGINT NOT NULL,
 input_file_name TEXT NOT NULL,
 ext TEXT NOT NULL
)`)
	if err != nil {
		t.Fatal(err)
	}
	_, err = pool.Exec(ctx, `CREATE TABLE documents (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 document_id BIGINT NOT NULL,
 access_hash BIGINT NOT NULL,
 dc_id INTEGER NOT NULL,
 file_path TEXT NOT NULL,
 file_size BIGINT NOT NULL DEFAULT 0,
 uploaded_file_name TEXT NOT NULL DEFAULT '',
 ext TEXT NOT NULL DEFAULT '',
 mime_type TEXT NOT NULL DEFAULT '',
 thumb_id BIGINT NOT NULL DEFAULT 0,
 video_thumb_id BIGINT NOT NULL DEFAULT 0,
 attributes JSONB NOT NULL DEFAULT '{}'::jsonb,
 version INTEGER NOT NULL DEFAULT 0,
 date2 BIGINT NOT NULL DEFAULT 0,
 import_document_id BIGINT NOT NULL DEFAULT 0,
 deleted BOOLEAN NOT NULL DEFAULT FALSE,
 sha256 BYTEA NOT NULL DEFAULT ''::bytea
)`)
	if err != nil {
		t.Fatal(err)
	}
	_, err = pool.Exec(ctx, `CREATE TABLE photo_sizes (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 photo_size_id BIGINT NOT NULL,
 size_type CHAR(1) NOT NULL CHECK (size_type <> 'z'),
 width INTEGER NOT NULL,
 height INTEGER NOT NULL,
 file_size INTEGER NOT NULL,
 file_path TEXT NOT NULL,
 cached_type INTEGER NOT NULL,
 cached_bytes TEXT NOT NULL
)`)
	if err != nil {
		t.Fatal(err)
	}
	_, err = pool.Exec(ctx, `CREATE TABLE video_sizes (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 video_size_id BIGINT NOT NULL,
 size_type CHAR(1) NOT NULL,
 width INTEGER NOT NULL,
 height INTEGER NOT NULL,
 file_size INTEGER NOT NULL,
 video_start_ts DOUBLE PRECISION NOT NULL,
 file_path TEXT NOT NULL
)`)
	if err != nil {
		t.Fatal(err)
	}
	store := postgres_dao.NewStore(pool)
	dao := &Dao{Postgres: &Postgres{
		Pool:          pool,
		DocumentsDAO:  store.Documents,
		PhotosDAO:     store.Photos,
		PhotoSizesDAO: store.PhotoSizes,
		VideoSizesDAO: store.VideoSizes,
	}}

	badSize := mtproto.MakeTLPhotoSize(&mtproto.PhotoSize{Type: "z", W: 10, H: 10, Size2: 20}).To_PhotoSize()
	videoSize := mtproto.MakeTLVideoSize(&mtproto.VideoSize{Type: "v", W: 20, H: 20, Size2: 30}).To_VideoSize()
	if err := dao.SavePhotoAggregateV2(ctx, 901, 902, false, true, "bad.jpg", []*mtproto.PhotoSize{badSize}, []*mtproto.VideoSize{videoSize}); err == nil {
		t.Fatal("SavePhotoAggregateV2 succeeded despite the photo-size constraint")
	}
	for _, table := range []string{"photos", "photo_sizes", "video_sizes"} {
		var count int
		if err := pool.QueryRow(ctx, `SELECT count(*) FROM `+table).Scan(&count); err != nil {
			t.Fatal(err)
		}
		if count != 0 {
			t.Fatalf("%s has %d rows after failed aggregate save, want 0", table, count)
		}
	}

	goodSize := mtproto.MakeTLPhotoSize(&mtproto.PhotoSize{Type: "x", W: 10, H: 10, Size2: 20}).To_PhotoSize()
	if err := dao.SavePhotoAggregateV2(ctx, 903, 904, true, true, "ok.jpg", []*mtproto.PhotoSize{goodSize}, []*mtproto.VideoSize{videoSize}); err != nil {
		t.Fatalf("SavePhotoAggregateV2 success path: %v", err)
	}
	if _, err := pool.Exec(ctx, `INSERT INTO documents
 (document_id, access_hash, dc_id, file_path, mime_type, thumb_id)
 VALUES (904, 905, 1, 'document.dat', 'image/jpeg', 903)`); err != nil {
		t.Fatal(err)
	}
	for table, want := range map[string]int{"photos": 1, "photo_sizes": 1, "video_sizes": 1} {
		var count int
		if err := pool.QueryRow(ctx, `SELECT count(*) FROM `+table).Scan(&count); err != nil {
			t.Fatal(err)
		}
		if count != want {
			t.Fatalf("%s has %d rows, want %d", table, count, want)
		}
	}
	photo, err := dao.GetPhotoV2(ctx, 903)
	if err != nil || photo.GetAccessHash() != 904 || len(photo.GetSizes()) != 1 || len(photo.GetVideoSizes()) != 1 {
		t.Fatalf("GetPhotoV2 = (%v, %v), want persisted photo and size rows", photo, err)
	}
	sizeLists, err := dao.GetPhotoSizeListListE(ctx, []int64{903})
	if err != nil || len(sizeLists[903]) != 1 {
		t.Fatalf("GetPhotoSizeListListE = (%v, %v), want persisted photo size", sizeLists, err)
	}
	document, err := dao.GetDocumentById(ctx, 904)
	if err != nil || len(document.GetThumbs()) != 1 {
		t.Fatalf("GetDocumentById = (%v, %v), want persisted thumbnail", document, err)
	}
	documents, err := dao.GetDocumentListByIdList(ctx, []int64{904})
	if err != nil || len(documents) != 1 || len(documents[0].GetThumbs()) != 1 {
		t.Fatalf("GetDocumentListByIdList = (%v, %v), want persisted thumbnail", documents, err)
	}
	if _, err := pool.Exec(ctx, `ALTER TABLE photo_sizes RENAME TO photo_sizes_unavailable`); err != nil {
		t.Fatal(err)
	}
	if _, err := dao.GetPhotoSizeListV2(ctx, 903); err == nil {
		t.Fatal("GetPhotoSizeListV2 hid the photo-size database error")
	}
	if _, err := dao.GetPhotoSizeListListE(ctx, []int64{903}); err == nil {
		t.Fatal("GetPhotoSizeListListE hid the photo-size database error")
	}
	if _, err := dao.GetPhotoV2(ctx, 903); err == nil {
		t.Fatal("GetPhotoV2 hid the photo-size database error")
	}
	if _, err := dao.GetDocumentById(ctx, 904); err == nil {
		t.Fatal("GetDocumentById hid the photo-size database error")
	}
	if _, err := dao.GetDocumentListByIdList(ctx, []int64{904}); err == nil {
		t.Fatal("GetDocumentListByIdList hid the photo-size database error")
	}
}
