// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: document_hash.proto

package hashrpc

import (
	mtproto "github.com/teamgram/proto/mtproto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DocumentHashRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sha256        []byte                 `protobuf:"bytes,1,opt,name=sha256,proto3" json:"sha256,omitempty"`
	Size          int64                  `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`
	MimeType      string                 `protobuf:"bytes,3,opt,name=mime_type,json=mimeType,proto3" json:"mime_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DocumentHashRequest) Reset() {
	*x = DocumentHashRequest{}
	mi := &file_document_hash_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DocumentHashRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DocumentHashRequest) ProtoMessage() {}

func (x *DocumentHashRequest) ProtoReflect() protoreflect.Message {
	mi := &file_document_hash_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DocumentHashRequest.ProtoReflect.Descriptor instead.
func (*DocumentHashRequest) Descriptor() ([]byte, []int) {
	return file_document_hash_proto_rawDescGZIP(), []int{0}
}

func (x *DocumentHashRequest) GetSha256() []byte {
	if x != nil {
		return x.Sha256
	}
	return nil
}

func (x *DocumentHashRequest) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *DocumentHashRequest) GetMimeType() string {
	if x != nil {
		return x.MimeType
	}
	return ""
}

var File_document_hash_proto protoreflect.FileDescriptor

const file_document_hash_proto_rawDesc = "" +
	"\n" +
	"\x13document_hash.proto\x12\tmediahash\x1a\x14schema.tl.sync.proto\"^\n" +
	"\x13DocumentHashRequest\x12\x16\n" +
	"\x06sha256\x18\x01 \x01(\fR\x06sha256\x12\x12\n" +
	"\x04size\x18\x02 \x01(\x03R\x04size\x12\x1b\n" +
	"\tmime_type\x18\x03 \x01(\tR\bmimeType2^\n" +
	"\x12DocumentHashLookup\x12H\n" +
	"\x11GetDocumentByHash\x12\x1e.mediahash.DocumentHashRequest\x1a\x11.mtproto.Document\"\x00BMZKgithub.com/teamgram/teamgram-server/app/service/media/media/hashrpc;hashrpcb\x06proto3"

var (
	file_document_hash_proto_rawDescOnce sync.Once
	file_document_hash_proto_rawDescData []byte
)

func file_document_hash_proto_rawDescGZIP() []byte {
	file_document_hash_proto_rawDescOnce.Do(func() {
		file_document_hash_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_document_hash_proto_rawDesc), len(file_document_hash_proto_rawDesc)))
	})
	return file_document_hash_proto_rawDescData
}

var file_document_hash_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_document_hash_proto_goTypes = []any{
	(*DocumentHashRequest)(nil), // 0: mediahash.DocumentHashRequest
	(*mtproto.Document)(nil),    // 1: mtproto.Document
}
var file_document_hash_proto_depIdxs = []int32{
	0, // 0: mediahash.DocumentHashLookup.GetDocumentByHash:input_type -> mediahash.DocumentHashRequest
	1, // 1: mediahash.DocumentHashLookup.GetDocumentByHash:output_type -> mtproto.Document
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_document_hash_proto_init() }
func file_document_hash_proto_init() {
	if File_document_hash_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_document_hash_proto_rawDesc), len(file_document_hash_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_document_hash_proto_goTypes,
		DependencyIndexes: file_document_hash_proto_depIdxs,
		MessageInfos:      file_document_hash_proto_msgTypes,
	}.Build()
	File_document_hash_proto = out.File
	file_document_hash_proto_goTypes = nil
	file_document_hash_proto_depIdxs = nil
}
