// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.3
// source: document_hash.proto

package hashrpc

import (
	context "context"
	mtproto "github.com/teamgram/proto/mtproto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	DocumentHashLookup_GetDocumentByHash_FullMethodName = "/mediahash.DocumentHashLookup/GetDocumentByHash"
)

// DocumentHashLookupClient is the client API for DocumentHashLookup service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DocumentHashLookupClient interface {
	GetDocumentByHash(ctx context.Context, in *DocumentHashRequest, opts ...grpc.CallOption) (*mtproto.Document, error)
}

type documentHashLookupClient struct {
	cc grpc.ClientConnInterface
}

func NewDocumentHashLookupClient(cc grpc.ClientConnInterface) DocumentHashLookupClient {
	return &documentHashLookupClient{cc}
}

func (c *documentHashLookupClient) GetDocumentByHash(ctx context.Context, in *DocumentHashRequest, opts ...grpc.CallOption) (*mtproto.Document, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(mtproto.Document)
	err := c.cc.Invoke(ctx, DocumentHashLookup_GetDocumentByHash_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DocumentHashLookupServer is the server API for DocumentHashLookup service.
// All implementations must embed UnimplementedDocumentHashLookupServer
// for forward compatibility.
type DocumentHashLookupServer interface {
	GetDocumentByHash(context.Context, *DocumentHashRequest) (*mtproto.Document, error)
	mustEmbedUnimplementedDocumentHashLookupServer()
}

// UnimplementedDocumentHashLookupServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDocumentHashLookupServer struct{}

func (UnimplementedDocumentHashLookupServer) GetDocumentByHash(context.Context, *DocumentHashRequest) (*mtproto.Document, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetDocumentByHash not implemented")
}
func (UnimplementedDocumentHashLookupServer) mustEmbedUnimplementedDocumentHashLookupServer() {}
func (UnimplementedDocumentHashLookupServer) testEmbeddedByValue()                            {}

// UnsafeDocumentHashLookupServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DocumentHashLookupServer will
// result in compilation errors.
type UnsafeDocumentHashLookupServer interface {
	mustEmbedUnimplementedDocumentHashLookupServer()
}

func RegisterDocumentHashLookupServer(s grpc.ServiceRegistrar, srv DocumentHashLookupServer) {
	// If the following call pancis, it indicates UnimplementedDocumentHashLookupServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&DocumentHashLookup_ServiceDesc, srv)
}

func _DocumentHashLookup_GetDocumentByHash_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DocumentHashRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DocumentHashLookupServer).GetDocumentByHash(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DocumentHashLookup_GetDocumentByHash_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DocumentHashLookupServer).GetDocumentByHash(ctx, req.(*DocumentHashRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// DocumentHashLookup_ServiceDesc is the grpc.ServiceDesc for DocumentHashLookup service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DocumentHashLookup_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "mediahash.DocumentHashLookup",
	HandlerType: (*DocumentHashLookupServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetDocumentByHash",
			Handler:    _DocumentHashLookup_GetDocumentByHash_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "document_hash.proto",
}
