package domain

import (
	"fmt"
	"regexp"
	"strings"
)

var (
	postgresTablePattern         = regexp.MustCompile(`(?is)CREATE\s+TABLE\s+IF\s+NOT\s+EXISTS\s+([a-z0-9_]+)`)
	postgresIndexPattern         = regexp.MustCompile(`(?m)^\s*KEY\s+([a-z0-9_]+)\s*\(([^)]*)\),?\s*$`)
	postgresUniquePattern        = regexp.MustCompile(`UNIQUE\s+KEY\s+([a-z0-9_]+)\s*\(([^)]*)\)`)
	postgresIdentityPattern      = regexp.MustCompile(`\b(BIGINT|INT)\s+NOT\s+NULL\s+AUTO_INCREMENT\b`)
	postgresEnginePattern        = regexp.MustCompile(`(?is)\)\s*ENGINE\s*=\s*[a-z0-9_]+(?:\s+DEFAULT\s+CHARSET\s*=\s*[a-z0-9_]+)?\s*$`)
	postgresTrailingCommaPattern = regexp.MustCompile(`,\s*\n\s*\)`)
)

// postgresDDL converts the canonical APIFull schema declarations used by the
// transitional MySQL path to PostgreSQL 18 DDL. Fresh PostgreSQL deployments
// execute the converted statements, so no historical column ALTER sequence is
// needed. Secondary KEY declarations become explicit indexes after creation.
func postgresDDL(mysqlDDL string) (string, []string, error) {
	match := postgresTablePattern.FindStringSubmatch(mysqlDDL)
	if len(match) != 2 {
		return "", nil, fmt.Errorf("apifull: cannot identify table in schema statement")
	}
	table := match[1]

	indexes := make([]string, 0)
	converted := postgresIndexPattern.ReplaceAllStringFunc(mysqlDDL, func(line string) string {
		parts := postgresIndexPattern.FindStringSubmatch(line)
		if len(parts) != 3 {
			return ""
		}
		indexes = append(indexes, fmt.Sprintf(
			"CREATE INDEX IF NOT EXISTS %s ON %s (%s)",
			parts[1], table, parts[2],
		))
		return ""
	})
	converted = postgresUniquePattern.ReplaceAllString(converted, "CONSTRAINT $1 UNIQUE ($2)")
	converted = postgresIdentityPattern.ReplaceAllString(converted, "$1 GENERATED BY DEFAULT AS IDENTITY")
	converted = strings.NewReplacer(
		"MEDIUMBLOB", "BYTEA",
		"LONGBLOB", "BYTEA",
		"VARBINARY(256)", "BYTEA",
		"VARBINARY(32)", "BYTEA",
		"BINARY(32)", "BYTEA",
		"MEDIUMTEXT", "TEXT",
		"TINYINT UNSIGNED", "SMALLINT",
		"TINYINT", "SMALLINT",
		"DOUBLE", "DOUBLE PRECISION",
		"UNSIGNED", "",
		" COLLATE utf8mb4_bin", "",
	).Replace(converted)
	converted = postgresEnginePattern.ReplaceAllString(converted, ")")
	converted = postgresTrailingCommaPattern.ReplaceAllString(converted, "\n)")
	return converted, indexes, nil
}
