// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.3
// source: bot_registry.proto

package user

import (
	context "context"
	mtproto "github.com/teamgram/proto/mtproto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	RPCBotRegistry_GetCreatedBots_FullMethodName = "/user.RPCBotRegistry/getCreatedBots"
	RPCBotRegistry_GetAdminedBots_FullMethodName = "/user.RPCBotRegistry/getAdminedBots"
	RPCBotRegistry_CreateBot_FullMethodName      = "/user.RPCBotRegistry/createBot"
	RPCBotRegistry_SetBotInfo_FullMethodName     = "/user.RPCBotRegistry/setBotInfo"
)

// RPCBotRegistryClient is the client API for RPCBotRegistry service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RPCBotRegistryClient interface {
	GetCreatedBots(ctx context.Context, in *BotRegistryGetCreatedBotsRequest, opts ...grpc.CallOption) (*Vector_ImmutableUser, error)
	GetAdminedBots(ctx context.Context, in *BotRegistryGetAdminedBotsRequest, opts ...grpc.CallOption) (*Vector_ImmutableUser, error)
	CreateBot(ctx context.Context, in *BotRegistryCreateBotRequest, opts ...grpc.CallOption) (*mtproto.ImmutableUser, error)
	SetBotInfo(ctx context.Context, in *BotRegistrySetBotInfoRequest, opts ...grpc.CallOption) (*mtproto.Bool, error)
}

type rPCBotRegistryClient struct {
	cc grpc.ClientConnInterface
}

func NewRPCBotRegistryClient(cc grpc.ClientConnInterface) RPCBotRegistryClient {
	return &rPCBotRegistryClient{cc}
}

func (c *rPCBotRegistryClient) GetCreatedBots(ctx context.Context, in *BotRegistryGetCreatedBotsRequest, opts ...grpc.CallOption) (*Vector_ImmutableUser, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Vector_ImmutableUser)
	err := c.cc.Invoke(ctx, RPCBotRegistry_GetCreatedBots_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rPCBotRegistryClient) GetAdminedBots(ctx context.Context, in *BotRegistryGetAdminedBotsRequest, opts ...grpc.CallOption) (*Vector_ImmutableUser, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Vector_ImmutableUser)
	err := c.cc.Invoke(ctx, RPCBotRegistry_GetAdminedBots_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rPCBotRegistryClient) CreateBot(ctx context.Context, in *BotRegistryCreateBotRequest, opts ...grpc.CallOption) (*mtproto.ImmutableUser, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(mtproto.ImmutableUser)
	err := c.cc.Invoke(ctx, RPCBotRegistry_CreateBot_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rPCBotRegistryClient) SetBotInfo(ctx context.Context, in *BotRegistrySetBotInfoRequest, opts ...grpc.CallOption) (*mtproto.Bool, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(mtproto.Bool)
	err := c.cc.Invoke(ctx, RPCBotRegistry_SetBotInfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RPCBotRegistryServer is the server API for RPCBotRegistry service.
// All implementations should embed UnimplementedRPCBotRegistryServer
// for forward compatibility.
type RPCBotRegistryServer interface {
	GetCreatedBots(context.Context, *BotRegistryGetCreatedBotsRequest) (*Vector_ImmutableUser, error)
	GetAdminedBots(context.Context, *BotRegistryGetAdminedBotsRequest) (*Vector_ImmutableUser, error)
	CreateBot(context.Context, *BotRegistryCreateBotRequest) (*mtproto.ImmutableUser, error)
	SetBotInfo(context.Context, *BotRegistrySetBotInfoRequest) (*mtproto.Bool, error)
}

// UnimplementedRPCBotRegistryServer should be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedRPCBotRegistryServer struct{}

func (UnimplementedRPCBotRegistryServer) GetCreatedBots(context.Context, *BotRegistryGetCreatedBotsRequest) (*Vector_ImmutableUser, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCreatedBots not implemented")
}
func (UnimplementedRPCBotRegistryServer) GetAdminedBots(context.Context, *BotRegistryGetAdminedBotsRequest) (*Vector_ImmutableUser, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAdminedBots not implemented")
}
func (UnimplementedRPCBotRegistryServer) CreateBot(context.Context, *BotRegistryCreateBotRequest) (*mtproto.ImmutableUser, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateBot not implemented")
}
func (UnimplementedRPCBotRegistryServer) SetBotInfo(context.Context, *BotRegistrySetBotInfoRequest) (*mtproto.Bool, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetBotInfo not implemented")
}
func (UnimplementedRPCBotRegistryServer) testEmbeddedByValue() {}

// UnsafeRPCBotRegistryServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RPCBotRegistryServer will
// result in compilation errors.
type UnsafeRPCBotRegistryServer interface {
	mustEmbedUnimplementedRPCBotRegistryServer()
}

func RegisterRPCBotRegistryServer(s grpc.ServiceRegistrar, srv RPCBotRegistryServer) {
	// If the following call pancis, it indicates UnimplementedRPCBotRegistryServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&RPCBotRegistry_ServiceDesc, srv)
}

func _RPCBotRegistry_GetCreatedBots_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BotRegistryGetCreatedBotsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RPCBotRegistryServer).GetCreatedBots(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RPCBotRegistry_GetCreatedBots_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RPCBotRegistryServer).GetCreatedBots(ctx, req.(*BotRegistryGetCreatedBotsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RPCBotRegistry_GetAdminedBots_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BotRegistryGetAdminedBotsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RPCBotRegistryServer).GetAdminedBots(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RPCBotRegistry_GetAdminedBots_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RPCBotRegistryServer).GetAdminedBots(ctx, req.(*BotRegistryGetAdminedBotsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RPCBotRegistry_CreateBot_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BotRegistryCreateBotRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RPCBotRegistryServer).CreateBot(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RPCBotRegistry_CreateBot_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RPCBotRegistryServer).CreateBot(ctx, req.(*BotRegistryCreateBotRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RPCBotRegistry_SetBotInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BotRegistrySetBotInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RPCBotRegistryServer).SetBotInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RPCBotRegistry_SetBotInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RPCBotRegistryServer).SetBotInfo(ctx, req.(*BotRegistrySetBotInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// RPCBotRegistry_ServiceDesc is the grpc.ServiceDesc for RPCBotRegistry service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RPCBotRegistry_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "user.RPCBotRegistry",
	HandlerType: (*RPCBotRegistryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "getCreatedBots",
			Handler:    _RPCBotRegistry_GetCreatedBots_Handler,
		},
		{
			MethodName: "getAdminedBots",
			Handler:    _RPCBotRegistry_GetAdminedBots_Handler,
		},
		{
			MethodName: "createBot",
			Handler:    _RPCBotRegistry_CreateBot_Handler,
		},
		{
			MethodName: "setBotInfo",
			Handler:    _RPCBotRegistry_SetBotInfo_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "bot_registry.proto",
}
