syntax = "proto3";

package user;

import "user.tl.proto";
import "schema.tl.core_types.proto";
import "schema.tl.sync.proto";
import "google/protobuf/wrappers.proto";

option go_package = "github.com/teamgram/teamgram-server/app/service/biz/user/user";

message BotRegistryGetCreatedBotsRequest {}

message BotRegistryGetAdminedBotsRequest {}

message BotRegistryCreateBotRequest {
  string name = 1;
  string username = 2;
  int64 manager_bot_id = 3;
  int64 manager_access_hash = 4;
}

message BotRegistrySetBotInfoRequest {
  int64 bot_id = 1;
  google.protobuf.StringValue name = 2;
  google.protobuf.StringValue about = 3;
  google.protobuf.StringValue description = 4;
}

service RPCBotRegistry {
  rpc getCreatedBots(BotRegistryGetCreatedBotsRequest)
      returns (Vector_ImmutableUser) {}
  rpc getAdminedBots(BotRegistryGetAdminedBotsRequest)
      returns (Vector_ImmutableUser) {}
  rpc createBot(BotRegistryCreateBotRequest)
      returns (mtproto.ImmutableUser) {}
  rpc setBotInfo(BotRegistrySetBotInfoRequest) returns (mtproto.Bool) {}
}
