//
// WARNING! All changes made in this file will be lost!
// Created from 'scheme.tl' by 'mtprotoc'
//
// Copyright (c) 2025-present,  Teamgram Authors.
//  All rights reserved.
//
// Author: Benqi (wubenqi@gmail.com)

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: msg.tl.proto

package msg

import (
	mtproto "github.com/teamgram/proto/mtproto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	wrapperspb "google.golang.org/protobuf/types/known/wrapperspb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TLConstructor int32

const (
	TLConstructor_CRC32_UNKNOWN                    TLConstructor = 0
	TLConstructor_CRC32_sender                     TLConstructor = 1513645242
	TLConstructor_CRC32_outboxMessage              TLConstructor = 1402283185
	TLConstructor_CRC32_contentMessage             TLConstructor = -1922780877
	TLConstructor_CRC32_msg_pushUserMessage        TLConstructor = 902887962
	TLConstructor_CRC32_msg_readMessageContents    TLConstructor = 673481940
	TLConstructor_CRC32_msg_sendMessageV2          TLConstructor = -188056380
	TLConstructor_CRC32_msg_editMessageV2          TLConstructor = 1778278369
	TLConstructor_CRC32_msg_deleteMessages         TLConstructor = 568855069
	TLConstructor_CRC32_msg_deleteHistory          TLConstructor = 1975576778
	TLConstructor_CRC32_msg_deletePhoneCallHistory TLConstructor = 649568574
	TLConstructor_CRC32_msg_deleteChatHistory      TLConstructor = -283155749
	TLConstructor_CRC32_msg_readHistory            TLConstructor = 1510960658
	TLConstructor_CRC32_msg_readMentions           TLConstructor = 292070214
	TLConstructor_CRC32_msg_readHistoryV2          TLConstructor = 263827974
	TLConstructor_CRC32_msg_updatePinnedMessage    TLConstructor = -441560663
	TLConstructor_CRC32_msg_unpinAllMessages       TLConstructor = -1199153371
)

// Enum value maps for TLConstructor.
var (
	TLConstructor_name = map[int32]string{
		0:           "CRC32_UNKNOWN",
		1513645242:  "CRC32_sender",
		1402283185:  "CRC32_outboxMessage",
		-1922780877: "CRC32_contentMessage",
		902887962:   "CRC32_msg_pushUserMessage",
		673481940:   "CRC32_msg_readMessageContents",
		-188056380:  "CRC32_msg_sendMessageV2",
		1778278369:  "CRC32_msg_editMessageV2",
		568855069:   "CRC32_msg_deleteMessages",
		1975576778:  "CRC32_msg_deleteHistory",
		649568574:   "CRC32_msg_deletePhoneCallHistory",
		-283155749:  "CRC32_msg_deleteChatHistory",
		1510960658:  "CRC32_msg_readHistory",
		292070214:   "CRC32_msg_readMentions",
		263827974:   "CRC32_msg_readHistoryV2",
		-441560663:  "CRC32_msg_updatePinnedMessage",
		-1199153371: "CRC32_msg_unpinAllMessages",
	}
	TLConstructor_value = map[string]int32{
		"CRC32_UNKNOWN":                    0,
		"CRC32_sender":                     1513645242,
		"CRC32_outboxMessage":              1402283185,
		"CRC32_contentMessage":             -1922780877,
		"CRC32_msg_pushUserMessage":        902887962,
		"CRC32_msg_readMessageContents":    673481940,
		"CRC32_msg_sendMessageV2":          -188056380,
		"CRC32_msg_editMessageV2":          1778278369,
		"CRC32_msg_deleteMessages":         568855069,
		"CRC32_msg_deleteHistory":          1975576778,
		"CRC32_msg_deletePhoneCallHistory": 649568574,
		"CRC32_msg_deleteChatHistory":      -283155749,
		"CRC32_msg_readHistory":            1510960658,
		"CRC32_msg_readMentions":           292070214,
		"CRC32_msg_readHistoryV2":          263827974,
		"CRC32_msg_updatePinnedMessage":    -441560663,
		"CRC32_msg_unpinAllMessages":       -1199153371,
	}
)

func (x TLConstructor) Enum() *TLConstructor {
	p := new(TLConstructor)
	*p = x
	return p
}

func (x TLConstructor) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TLConstructor) Descriptor() protoreflect.EnumDescriptor {
	return file_msg_tl_proto_enumTypes[0].Descriptor()
}

func (TLConstructor) Type() protoreflect.EnumType {
	return &file_msg_tl_proto_enumTypes[0]
}

func (x TLConstructor) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TLConstructor.Descriptor instead.
func (TLConstructor) EnumDescriptor() ([]byte, []int) {
	return file_msg_tl_proto_rawDescGZIP(), []int{0}
}

// ContentMessage <--
//   - TL_contentMessage
type ContentMessage struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	PredicateName   string                 `protobuf:"bytes,1,opt,name=predicate_name,json=predicateName,proto3" json:"predicate_name,omitempty"`
	Constructor     TLConstructor          `protobuf:"varint,2,opt,name=constructor,proto3,enum=msg.TLConstructor" json:"constructor,omitempty"`
	Id              int32                  `protobuf:"varint,3,opt,name=id,proto3" json:"id,omitempty"`
	DialogMessageId int64                  `protobuf:"varint,4,opt,name=dialog_message_id,json=dialogMessageId,proto3" json:"dialog_message_id,omitempty"`
	Mentioned       bool                   `protobuf:"varint,5,opt,name=mentioned,proto3" json:"mentioned,omitempty"`
	MediaUnread     bool                   `protobuf:"varint,6,opt,name=media_unread,json=mediaUnread,proto3" json:"media_unread,omitempty"`
	Reaction        bool                   `protobuf:"varint,7,opt,name=reaction,proto3" json:"reaction,omitempty"`
	SendUserId      int64                  `protobuf:"varint,8,opt,name=send_user_id,json=sendUserId,proto3" json:"send_user_id,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ContentMessage) Reset() {
	*x = ContentMessage{}
	mi := &file_msg_tl_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContentMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContentMessage) ProtoMessage() {}

func (x *ContentMessage) ProtoReflect() protoreflect.Message {
	mi := &file_msg_tl_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContentMessage.ProtoReflect.Descriptor instead.
func (*ContentMessage) Descriptor() ([]byte, []int) {
	return file_msg_tl_proto_rawDescGZIP(), []int{0}
}

func (x *ContentMessage) GetPredicateName() string {
	if x != nil {
		return x.PredicateName
	}
	return ""
}

func (x *ContentMessage) GetConstructor() TLConstructor {
	if x != nil {
		return x.Constructor
	}
	return TLConstructor_CRC32_UNKNOWN
}

func (x *ContentMessage) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ContentMessage) GetDialogMessageId() int64 {
	if x != nil {
		return x.DialogMessageId
	}
	return 0
}

func (x *ContentMessage) GetMentioned() bool {
	if x != nil {
		return x.Mentioned
	}
	return false
}

func (x *ContentMessage) GetMediaUnread() bool {
	if x != nil {
		return x.MediaUnread
	}
	return false
}

func (x *ContentMessage) GetReaction() bool {
	if x != nil {
		return x.Reaction
	}
	return false
}

func (x *ContentMessage) GetSendUserId() int64 {
	if x != nil {
		return x.SendUserId
	}
	return 0
}

type TLContentMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data2         *ContentMessage        `protobuf:"bytes,1,opt,name=data2,proto3" json:"data2,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TLContentMessage) Reset() {
	*x = TLContentMessage{}
	mi := &file_msg_tl_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TLContentMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TLContentMessage) ProtoMessage() {}

func (x *TLContentMessage) ProtoReflect() protoreflect.Message {
	mi := &file_msg_tl_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TLContentMessage.ProtoReflect.Descriptor instead.
func (*TLContentMessage) Descriptor() ([]byte, []int) {
	return file_msg_tl_proto_rawDescGZIP(), []int{1}
}

func (x *TLContentMessage) GetData2() *ContentMessage {
	if x != nil {
		return x.Data2
	}
	return nil
}

// OutboxMessage <--
//   - TL_outboxMessage
type OutboxMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PredicateName string                 `protobuf:"bytes,1,opt,name=predicate_name,json=predicateName,proto3" json:"predicate_name,omitempty"`
	Constructor   TLConstructor          `protobuf:"varint,2,opt,name=constructor,proto3,enum=msg.TLConstructor" json:"constructor,omitempty"`
	NoWebpage     bool                   `protobuf:"varint,3,opt,name=no_webpage,json=noWebpage,proto3" json:"no_webpage,omitempty"`
	Background    bool                   `protobuf:"varint,4,opt,name=background,proto3" json:"background,omitempty"`
	RandomId      int64                  `protobuf:"varint,5,opt,name=random_id,json=randomId,proto3" json:"random_id,omitempty"`
	Message       *mtproto.Message       `protobuf:"bytes,6,opt,name=message,proto3" json:"message,omitempty"`
	ScheduleDate  *wrapperspb.Int32Value `protobuf:"bytes,7,opt,name=schedule_date,json=scheduleDate,proto3" json:"schedule_date,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OutboxMessage) Reset() {
	*x = OutboxMessage{}
	mi := &file_msg_tl_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OutboxMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OutboxMessage) ProtoMessage() {}

func (x *OutboxMessage) ProtoReflect() protoreflect.Message {
	mi := &file_msg_tl_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OutboxMessage.ProtoReflect.Descriptor instead.
func (*OutboxMessage) Descriptor() ([]byte, []int) {
	return file_msg_tl_proto_rawDescGZIP(), []int{2}
}

func (x *OutboxMessage) GetPredicateName() string {
	if x != nil {
		return x.PredicateName
	}
	return ""
}

func (x *OutboxMessage) GetConstructor() TLConstructor {
	if x != nil {
		return x.Constructor
	}
	return TLConstructor_CRC32_UNKNOWN
}

func (x *OutboxMessage) GetNoWebpage() bool {
	if x != nil {
		return x.NoWebpage
	}
	return false
}

func (x *OutboxMessage) GetBackground() bool {
	if x != nil {
		return x.Background
	}
	return false
}

func (x *OutboxMessage) GetRandomId() int64 {
	if x != nil {
		return x.RandomId
	}
	return 0
}

func (x *OutboxMessage) GetMessage() *mtproto.Message {
	if x != nil {
		return x.Message
	}
	return nil
}

func (x *OutboxMessage) GetScheduleDate() *wrapperspb.Int32Value {
	if x != nil {
		return x.ScheduleDate
	}
	return nil
}

type TLOutboxMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data2         *OutboxMessage         `protobuf:"bytes,1,opt,name=data2,proto3" json:"data2,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TLOutboxMessage) Reset() {
	*x = TLOutboxMessage{}
	mi := &file_msg_tl_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TLOutboxMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TLOutboxMessage) ProtoMessage() {}

func (x *TLOutboxMessage) ProtoReflect() protoreflect.Message {
	mi := &file_msg_tl_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TLOutboxMessage.ProtoReflect.Descriptor instead.
func (*TLOutboxMessage) Descriptor() ([]byte, []int) {
	return file_msg_tl_proto_rawDescGZIP(), []int{3}
}

func (x *TLOutboxMessage) GetData2() *OutboxMessage {
	if x != nil {
		return x.Data2
	}
	return nil
}

// Sender <--
//   - TL_sender
type Sender struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PredicateName string                 `protobuf:"bytes,1,opt,name=predicate_name,json=predicateName,proto3" json:"predicate_name,omitempty"`
	Constructor   TLConstructor          `protobuf:"varint,2,opt,name=constructor,proto3,enum=msg.TLConstructor" json:"constructor,omitempty"`
	UserId        int64                  `protobuf:"varint,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Type          int32                  `protobuf:"varint,4,opt,name=type,proto3" json:"type,omitempty"`
	AuthKeyId     int64                  `protobuf:"varint,5,opt,name=auth_key_id,json=authKeyId,proto3" json:"auth_key_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Sender) Reset() {
	*x = Sender{}
	mi := &file_msg_tl_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Sender) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Sender) ProtoMessage() {}

func (x *Sender) ProtoReflect() protoreflect.Message {
	mi := &file_msg_tl_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Sender.ProtoReflect.Descriptor instead.
func (*Sender) Descriptor() ([]byte, []int) {
	return file_msg_tl_proto_rawDescGZIP(), []int{4}
}

func (x *Sender) GetPredicateName() string {
	if x != nil {
		return x.PredicateName
	}
	return ""
}

func (x *Sender) GetConstructor() TLConstructor {
	if x != nil {
		return x.Constructor
	}
	return TLConstructor_CRC32_UNKNOWN
}

func (x *Sender) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *Sender) GetType() int32 {
	if x != nil {
		return x.Type
	}
	return 0
}

func (x *Sender) GetAuthKeyId() int64 {
	if x != nil {
		return x.AuthKeyId
	}
	return 0
}

type TLSender struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data2         *Sender                `protobuf:"bytes,1,opt,name=data2,proto3" json:"data2,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TLSender) Reset() {
	*x = TLSender{}
	mi := &file_msg_tl_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TLSender) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TLSender) ProtoMessage() {}

func (x *TLSender) ProtoReflect() protoreflect.Message {
	mi := &file_msg_tl_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TLSender.ProtoReflect.Descriptor instead.
func (*TLSender) Descriptor() ([]byte, []int) {
	return file_msg_tl_proto_rawDescGZIP(), []int{5}
}

func (x *TLSender) GetData2() *Sender {
	if x != nil {
		return x.Data2
	}
	return nil
}

// --------------------------------------------------------------------------------------------
type TLMsgPushUserMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Constructor   TLConstructor          `protobuf:"varint,1,opt,name=constructor,proto3,enum=msg.TLConstructor" json:"constructor,omitempty"`
	UserId        int64                  `protobuf:"varint,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	AuthKeyId     int64                  `protobuf:"varint,4,opt,name=auth_key_id,json=authKeyId,proto3" json:"auth_key_id,omitempty"`
	PeerType      int32                  `protobuf:"varint,5,opt,name=peer_type,json=peerType,proto3" json:"peer_type,omitempty"`
	PeerId        int64                  `protobuf:"varint,6,opt,name=peer_id,json=peerId,proto3" json:"peer_id,omitempty"`
	PushType      int32                  `protobuf:"varint,7,opt,name=push_type,json=pushType,proto3" json:"push_type,omitempty"`
	Message       *OutboxMessage         `protobuf:"bytes,8,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TLMsgPushUserMessage) Reset() {
	*x = TLMsgPushUserMessage{}
	mi := &file_msg_tl_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TLMsgPushUserMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TLMsgPushUserMessage) ProtoMessage() {}

func (x *TLMsgPushUserMessage) ProtoReflect() protoreflect.Message {
	mi := &file_msg_tl_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TLMsgPushUserMessage.ProtoReflect.Descriptor instead.
func (*TLMsgPushUserMessage) Descriptor() ([]byte, []int) {
	return file_msg_tl_proto_rawDescGZIP(), []int{6}
}

func (x *TLMsgPushUserMessage) GetConstructor() TLConstructor {
	if x != nil {
		return x.Constructor
	}
	return TLConstructor_CRC32_UNKNOWN
}

func (x *TLMsgPushUserMessage) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *TLMsgPushUserMessage) GetAuthKeyId() int64 {
	if x != nil {
		return x.AuthKeyId
	}
	return 0
}

func (x *TLMsgPushUserMessage) GetPeerType() int32 {
	if x != nil {
		return x.PeerType
	}
	return 0
}

func (x *TLMsgPushUserMessage) GetPeerId() int64 {
	if x != nil {
		return x.PeerId
	}
	return 0
}

func (x *TLMsgPushUserMessage) GetPushType() int32 {
	if x != nil {
		return x.PushType
	}
	return 0
}

func (x *TLMsgPushUserMessage) GetMessage() *OutboxMessage {
	if x != nil {
		return x.Message
	}
	return nil
}

// --------------------------------------------------------------------------------------------
type TLMsgReadMessageContents struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Constructor   TLConstructor          `protobuf:"varint,1,opt,name=constructor,proto3,enum=msg.TLConstructor" json:"constructor,omitempty"`
	UserId        int64                  `protobuf:"varint,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	AuthKeyId     int64                  `protobuf:"varint,4,opt,name=auth_key_id,json=authKeyId,proto3" json:"auth_key_id,omitempty"`
	PeerType      int32                  `protobuf:"varint,5,opt,name=peer_type,json=peerType,proto3" json:"peer_type,omitempty"`
	PeerId        int64                  `protobuf:"varint,6,opt,name=peer_id,json=peerId,proto3" json:"peer_id,omitempty"`
	Id            []*ContentMessage      `protobuf:"bytes,7,rep,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TLMsgReadMessageContents) Reset() {
	*x = TLMsgReadMessageContents{}
	mi := &file_msg_tl_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TLMsgReadMessageContents) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TLMsgReadMessageContents) ProtoMessage() {}

func (x *TLMsgReadMessageContents) ProtoReflect() protoreflect.Message {
	mi := &file_msg_tl_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TLMsgReadMessageContents.ProtoReflect.Descriptor instead.
func (*TLMsgReadMessageContents) Descriptor() ([]byte, []int) {
	return file_msg_tl_proto_rawDescGZIP(), []int{7}
}

func (x *TLMsgReadMessageContents) GetConstructor() TLConstructor {
	if x != nil {
		return x.Constructor
	}
	return TLConstructor_CRC32_UNKNOWN
}

func (x *TLMsgReadMessageContents) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *TLMsgReadMessageContents) GetAuthKeyId() int64 {
	if x != nil {
		return x.AuthKeyId
	}
	return 0
}

func (x *TLMsgReadMessageContents) GetPeerType() int32 {
	if x != nil {
		return x.PeerType
	}
	return 0
}

func (x *TLMsgReadMessageContents) GetPeerId() int64 {
	if x != nil {
		return x.PeerId
	}
	return 0
}

func (x *TLMsgReadMessageContents) GetId() []*ContentMessage {
	if x != nil {
		return x.Id
	}
	return nil
}

// --------------------------------------------------------------------------------------------
type TLMsgSendMessageV2 struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Constructor   TLConstructor          `protobuf:"varint,1,opt,name=constructor,proto3,enum=msg.TLConstructor" json:"constructor,omitempty"`
	UserId        int64                  `protobuf:"varint,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	AuthKeyId     int64                  `protobuf:"varint,4,opt,name=auth_key_id,json=authKeyId,proto3" json:"auth_key_id,omitempty"`
	PeerType      int32                  `protobuf:"varint,5,opt,name=peer_type,json=peerType,proto3" json:"peer_type,omitempty"`
	PeerId        int64                  `protobuf:"varint,6,opt,name=peer_id,json=peerId,proto3" json:"peer_id,omitempty"`
	Message       []*OutboxMessage       `protobuf:"bytes,7,rep,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TLMsgSendMessageV2) Reset() {
	*x = TLMsgSendMessageV2{}
	mi := &file_msg_tl_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TLMsgSendMessageV2) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TLMsgSendMessageV2) ProtoMessage() {}

func (x *TLMsgSendMessageV2) ProtoReflect() protoreflect.Message {
	mi := &file_msg_tl_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TLMsgSendMessageV2.ProtoReflect.Descriptor instead.
func (*TLMsgSendMessageV2) Descriptor() ([]byte, []int) {
	return file_msg_tl_proto_rawDescGZIP(), []int{8}
}

func (x *TLMsgSendMessageV2) GetConstructor() TLConstructor {
	if x != nil {
		return x.Constructor
	}
	return TLConstructor_CRC32_UNKNOWN
}

func (x *TLMsgSendMessageV2) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *TLMsgSendMessageV2) GetAuthKeyId() int64 {
	if x != nil {
		return x.AuthKeyId
	}
	return 0
}

func (x *TLMsgSendMessageV2) GetPeerType() int32 {
	if x != nil {
		return x.PeerType
	}
	return 0
}

func (x *TLMsgSendMessageV2) GetPeerId() int64 {
	if x != nil {
		return x.PeerId
	}
	return 0
}

func (x *TLMsgSendMessageV2) GetMessage() []*OutboxMessage {
	if x != nil {
		return x.Message
	}
	return nil
}

// --------------------------------------------------------------------------------------------
type TLMsgEditMessageV2 struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Constructor   TLConstructor          `protobuf:"varint,1,opt,name=constructor,proto3,enum=msg.TLConstructor" json:"constructor,omitempty"`
	UserId        int64                  `protobuf:"varint,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	AuthKeyId     int64                  `protobuf:"varint,4,opt,name=auth_key_id,json=authKeyId,proto3" json:"auth_key_id,omitempty"`
	PeerType      int32                  `protobuf:"varint,5,opt,name=peer_type,json=peerType,proto3" json:"peer_type,omitempty"`
	PeerId        int64                  `protobuf:"varint,6,opt,name=peer_id,json=peerId,proto3" json:"peer_id,omitempty"`
	EditType      int32                  `protobuf:"varint,7,opt,name=edit_type,json=editType,proto3" json:"edit_type,omitempty"`
	NewMessage    *OutboxMessage         `protobuf:"bytes,8,opt,name=new_message,json=newMessage,proto3" json:"new_message,omitempty"`
	DstMessage    *mtproto.MessageBox    `protobuf:"bytes,9,opt,name=dst_message,json=dstMessage,proto3" json:"dst_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TLMsgEditMessageV2) Reset() {
	*x = TLMsgEditMessageV2{}
	mi := &file_msg_tl_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TLMsgEditMessageV2) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TLMsgEditMessageV2) ProtoMessage() {}

func (x *TLMsgEditMessageV2) ProtoReflect() protoreflect.Message {
	mi := &file_msg_tl_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TLMsgEditMessageV2.ProtoReflect.Descriptor instead.
func (*TLMsgEditMessageV2) Descriptor() ([]byte, []int) {
	return file_msg_tl_proto_rawDescGZIP(), []int{9}
}

func (x *TLMsgEditMessageV2) GetConstructor() TLConstructor {
	if x != nil {
		return x.Constructor
	}
	return TLConstructor_CRC32_UNKNOWN
}

func (x *TLMsgEditMessageV2) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *TLMsgEditMessageV2) GetAuthKeyId() int64 {
	if x != nil {
		return x.AuthKeyId
	}
	return 0
}

func (x *TLMsgEditMessageV2) GetPeerType() int32 {
	if x != nil {
		return x.PeerType
	}
	return 0
}

func (x *TLMsgEditMessageV2) GetPeerId() int64 {
	if x != nil {
		return x.PeerId
	}
	return 0
}

func (x *TLMsgEditMessageV2) GetEditType() int32 {
	if x != nil {
		return x.EditType
	}
	return 0
}

func (x *TLMsgEditMessageV2) GetNewMessage() *OutboxMessage {
	if x != nil {
		return x.NewMessage
	}
	return nil
}

func (x *TLMsgEditMessageV2) GetDstMessage() *mtproto.MessageBox {
	if x != nil {
		return x.DstMessage
	}
	return nil
}

// --------------------------------------------------------------------------------------------
type TLMsgDeleteMessages struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Constructor   TLConstructor          `protobuf:"varint,1,opt,name=constructor,proto3,enum=msg.TLConstructor" json:"constructor,omitempty"`
	UserId        int64                  `protobuf:"varint,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	AuthKeyId     int64                  `protobuf:"varint,4,opt,name=auth_key_id,json=authKeyId,proto3" json:"auth_key_id,omitempty"`
	PeerType      int32                  `protobuf:"varint,5,opt,name=peer_type,json=peerType,proto3" json:"peer_type,omitempty"`
	PeerId        int64                  `protobuf:"varint,6,opt,name=peer_id,json=peerId,proto3" json:"peer_id,omitempty"`
	Revoke        bool                   `protobuf:"varint,7,opt,name=revoke,proto3" json:"revoke,omitempty"`
	Id            []int32                `protobuf:"varint,8,rep,packed,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TLMsgDeleteMessages) Reset() {
	*x = TLMsgDeleteMessages{}
	mi := &file_msg_tl_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TLMsgDeleteMessages) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TLMsgDeleteMessages) ProtoMessage() {}

func (x *TLMsgDeleteMessages) ProtoReflect() protoreflect.Message {
	mi := &file_msg_tl_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TLMsgDeleteMessages.ProtoReflect.Descriptor instead.
func (*TLMsgDeleteMessages) Descriptor() ([]byte, []int) {
	return file_msg_tl_proto_rawDescGZIP(), []int{10}
}

func (x *TLMsgDeleteMessages) GetConstructor() TLConstructor {
	if x != nil {
		return x.Constructor
	}
	return TLConstructor_CRC32_UNKNOWN
}

func (x *TLMsgDeleteMessages) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *TLMsgDeleteMessages) GetAuthKeyId() int64 {
	if x != nil {
		return x.AuthKeyId
	}
	return 0
}

func (x *TLMsgDeleteMessages) GetPeerType() int32 {
	if x != nil {
		return x.PeerType
	}
	return 0
}

func (x *TLMsgDeleteMessages) GetPeerId() int64 {
	if x != nil {
		return x.PeerId
	}
	return 0
}

func (x *TLMsgDeleteMessages) GetRevoke() bool {
	if x != nil {
		return x.Revoke
	}
	return false
}

func (x *TLMsgDeleteMessages) GetId() []int32 {
	if x != nil {
		return x.Id
	}
	return nil
}

// --------------------------------------------------------------------------------------------
type TLMsgDeleteHistory struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Constructor   TLConstructor          `protobuf:"varint,1,opt,name=constructor,proto3,enum=msg.TLConstructor" json:"constructor,omitempty"`
	UserId        int64                  `protobuf:"varint,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	AuthKeyId     int64                  `protobuf:"varint,4,opt,name=auth_key_id,json=authKeyId,proto3" json:"auth_key_id,omitempty"`
	PeerType      int32                  `protobuf:"varint,5,opt,name=peer_type,json=peerType,proto3" json:"peer_type,omitempty"`
	PeerId        int64                  `protobuf:"varint,6,opt,name=peer_id,json=peerId,proto3" json:"peer_id,omitempty"`
	JustClear     bool                   `protobuf:"varint,7,opt,name=just_clear,json=justClear,proto3" json:"just_clear,omitempty"`
	Revoke        bool                   `protobuf:"varint,8,opt,name=revoke,proto3" json:"revoke,omitempty"`
	MaxId         int32                  `protobuf:"varint,9,opt,name=max_id,json=maxId,proto3" json:"max_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TLMsgDeleteHistory) Reset() {
	*x = TLMsgDeleteHistory{}
	mi := &file_msg_tl_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TLMsgDeleteHistory) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TLMsgDeleteHistory) ProtoMessage() {}

func (x *TLMsgDeleteHistory) ProtoReflect() protoreflect.Message {
	mi := &file_msg_tl_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TLMsgDeleteHistory.ProtoReflect.Descriptor instead.
func (*TLMsgDeleteHistory) Descriptor() ([]byte, []int) {
	return file_msg_tl_proto_rawDescGZIP(), []int{11}
}

func (x *TLMsgDeleteHistory) GetConstructor() TLConstructor {
	if x != nil {
		return x.Constructor
	}
	return TLConstructor_CRC32_UNKNOWN
}

func (x *TLMsgDeleteHistory) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *TLMsgDeleteHistory) GetAuthKeyId() int64 {
	if x != nil {
		return x.AuthKeyId
	}
	return 0
}

func (x *TLMsgDeleteHistory) GetPeerType() int32 {
	if x != nil {
		return x.PeerType
	}
	return 0
}

func (x *TLMsgDeleteHistory) GetPeerId() int64 {
	if x != nil {
		return x.PeerId
	}
	return 0
}

func (x *TLMsgDeleteHistory) GetJustClear() bool {
	if x != nil {
		return x.JustClear
	}
	return false
}

func (x *TLMsgDeleteHistory) GetRevoke() bool {
	if x != nil {
		return x.Revoke
	}
	return false
}

func (x *TLMsgDeleteHistory) GetMaxId() int32 {
	if x != nil {
		return x.MaxId
	}
	return 0
}

// --------------------------------------------------------------------------------------------
type TLMsgDeletePhoneCallHistory struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Constructor   TLConstructor          `protobuf:"varint,1,opt,name=constructor,proto3,enum=msg.TLConstructor" json:"constructor,omitempty"`
	UserId        int64                  `protobuf:"varint,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	AuthKeyId     int64                  `protobuf:"varint,4,opt,name=auth_key_id,json=authKeyId,proto3" json:"auth_key_id,omitempty"`
	Revoke        bool                   `protobuf:"varint,5,opt,name=revoke,proto3" json:"revoke,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TLMsgDeletePhoneCallHistory) Reset() {
	*x = TLMsgDeletePhoneCallHistory{}
	mi := &file_msg_tl_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TLMsgDeletePhoneCallHistory) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TLMsgDeletePhoneCallHistory) ProtoMessage() {}

func (x *TLMsgDeletePhoneCallHistory) ProtoReflect() protoreflect.Message {
	mi := &file_msg_tl_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TLMsgDeletePhoneCallHistory.ProtoReflect.Descriptor instead.
func (*TLMsgDeletePhoneCallHistory) Descriptor() ([]byte, []int) {
	return file_msg_tl_proto_rawDescGZIP(), []int{12}
}

func (x *TLMsgDeletePhoneCallHistory) GetConstructor() TLConstructor {
	if x != nil {
		return x.Constructor
	}
	return TLConstructor_CRC32_UNKNOWN
}

func (x *TLMsgDeletePhoneCallHistory) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *TLMsgDeletePhoneCallHistory) GetAuthKeyId() int64 {
	if x != nil {
		return x.AuthKeyId
	}
	return 0
}

func (x *TLMsgDeletePhoneCallHistory) GetRevoke() bool {
	if x != nil {
		return x.Revoke
	}
	return false
}

// --------------------------------------------------------------------------------------------
type TLMsgDeleteChatHistory struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Constructor   TLConstructor          `protobuf:"varint,1,opt,name=constructor,proto3,enum=msg.TLConstructor" json:"constructor,omitempty"`
	ChatId        int64                  `protobuf:"varint,3,opt,name=chat_id,json=chatId,proto3" json:"chat_id,omitempty"`
	DeleteUserId  int64                  `protobuf:"varint,4,opt,name=delete_user_id,json=deleteUserId,proto3" json:"delete_user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TLMsgDeleteChatHistory) Reset() {
	*x = TLMsgDeleteChatHistory{}
	mi := &file_msg_tl_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TLMsgDeleteChatHistory) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TLMsgDeleteChatHistory) ProtoMessage() {}

func (x *TLMsgDeleteChatHistory) ProtoReflect() protoreflect.Message {
	mi := &file_msg_tl_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TLMsgDeleteChatHistory.ProtoReflect.Descriptor instead.
func (*TLMsgDeleteChatHistory) Descriptor() ([]byte, []int) {
	return file_msg_tl_proto_rawDescGZIP(), []int{13}
}

func (x *TLMsgDeleteChatHistory) GetConstructor() TLConstructor {
	if x != nil {
		return x.Constructor
	}
	return TLConstructor_CRC32_UNKNOWN
}

func (x *TLMsgDeleteChatHistory) GetChatId() int64 {
	if x != nil {
		return x.ChatId
	}
	return 0
}

func (x *TLMsgDeleteChatHistory) GetDeleteUserId() int64 {
	if x != nil {
		return x.DeleteUserId
	}
	return 0
}

// --------------------------------------------------------------------------------------------
type TLMsgReadHistory struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Constructor   TLConstructor          `protobuf:"varint,1,opt,name=constructor,proto3,enum=msg.TLConstructor" json:"constructor,omitempty"`
	UserId        int64                  `protobuf:"varint,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	AuthKeyId     int64                  `protobuf:"varint,4,opt,name=auth_key_id,json=authKeyId,proto3" json:"auth_key_id,omitempty"`
	PeerType      int32                  `protobuf:"varint,5,opt,name=peer_type,json=peerType,proto3" json:"peer_type,omitempty"`
	PeerId        int64                  `protobuf:"varint,6,opt,name=peer_id,json=peerId,proto3" json:"peer_id,omitempty"`
	MaxId         int32                  `protobuf:"varint,7,opt,name=max_id,json=maxId,proto3" json:"max_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TLMsgReadHistory) Reset() {
	*x = TLMsgReadHistory{}
	mi := &file_msg_tl_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TLMsgReadHistory) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TLMsgReadHistory) ProtoMessage() {}

func (x *TLMsgReadHistory) ProtoReflect() protoreflect.Message {
	mi := &file_msg_tl_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TLMsgReadHistory.ProtoReflect.Descriptor instead.
func (*TLMsgReadHistory) Descriptor() ([]byte, []int) {
	return file_msg_tl_proto_rawDescGZIP(), []int{14}
}

func (x *TLMsgReadHistory) GetConstructor() TLConstructor {
	if x != nil {
		return x.Constructor
	}
	return TLConstructor_CRC32_UNKNOWN
}

func (x *TLMsgReadHistory) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *TLMsgReadHistory) GetAuthKeyId() int64 {
	if x != nil {
		return x.AuthKeyId
	}
	return 0
}

func (x *TLMsgReadHistory) GetPeerType() int32 {
	if x != nil {
		return x.PeerType
	}
	return 0
}

func (x *TLMsgReadHistory) GetPeerId() int64 {
	if x != nil {
		return x.PeerId
	}
	return 0
}

func (x *TLMsgReadHistory) GetMaxId() int32 {
	if x != nil {
		return x.MaxId
	}
	return 0
}

// --------------------------------------------------------------------------------------------
type TLMsgReadHistoryV2 struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Constructor   TLConstructor          `protobuf:"varint,1,opt,name=constructor,proto3,enum=msg.TLConstructor" json:"constructor,omitempty"`
	UserId        int64                  `protobuf:"varint,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	AuthKeyId     int64                  `protobuf:"varint,4,opt,name=auth_key_id,json=authKeyId,proto3" json:"auth_key_id,omitempty"`
	PeerType      int32                  `protobuf:"varint,5,opt,name=peer_type,json=peerType,proto3" json:"peer_type,omitempty"`
	PeerId        int64                  `protobuf:"varint,6,opt,name=peer_id,json=peerId,proto3" json:"peer_id,omitempty"`
	MaxId         int32                  `protobuf:"varint,7,opt,name=max_id,json=maxId,proto3" json:"max_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TLMsgReadHistoryV2) Reset() {
	*x = TLMsgReadHistoryV2{}
	mi := &file_msg_tl_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TLMsgReadHistoryV2) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TLMsgReadHistoryV2) ProtoMessage() {}

func (x *TLMsgReadHistoryV2) ProtoReflect() protoreflect.Message {
	mi := &file_msg_tl_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TLMsgReadHistoryV2.ProtoReflect.Descriptor instead.
func (*TLMsgReadHistoryV2) Descriptor() ([]byte, []int) {
	return file_msg_tl_proto_rawDescGZIP(), []int{15}
}

func (x *TLMsgReadHistoryV2) GetConstructor() TLConstructor {
	if x != nil {
		return x.Constructor
	}
	return TLConstructor_CRC32_UNKNOWN
}

func (x *TLMsgReadHistoryV2) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *TLMsgReadHistoryV2) GetAuthKeyId() int64 {
	if x != nil {
		return x.AuthKeyId
	}
	return 0
}

func (x *TLMsgReadHistoryV2) GetPeerType() int32 {
	if x != nil {
		return x.PeerType
	}
	return 0
}

func (x *TLMsgReadHistoryV2) GetPeerId() int64 {
	if x != nil {
		return x.PeerId
	}
	return 0
}

func (x *TLMsgReadHistoryV2) GetMaxId() int32 {
	if x != nil {
		return x.MaxId
	}
	return 0
}

// --------------------------------------------------------------------------------------------
type TLMsgReadMentions struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Constructor   TLConstructor          `protobuf:"varint,1,opt,name=constructor,proto3,enum=msg.TLConstructor" json:"constructor,omitempty"`
	UserId        int64                  `protobuf:"varint,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	AuthKeyId     int64                  `protobuf:"varint,4,opt,name=auth_key_id,json=authKeyId,proto3" json:"auth_key_id,omitempty"`
	PeerType      int32                  `protobuf:"varint,5,opt,name=peer_type,json=peerType,proto3" json:"peer_type,omitempty"`
	PeerId        int64                  `protobuf:"varint,6,opt,name=peer_id,json=peerId,proto3" json:"peer_id,omitempty"`
	TopMsgId      *wrapperspb.Int32Value `protobuf:"bytes,7,opt,name=top_msg_id,json=topMsgId,proto3" json:"top_msg_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TLMsgReadMentions) Reset() {
	*x = TLMsgReadMentions{}
	mi := &file_msg_tl_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TLMsgReadMentions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TLMsgReadMentions) ProtoMessage() {}

func (x *TLMsgReadMentions) ProtoReflect() protoreflect.Message {
	mi := &file_msg_tl_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TLMsgReadMentions.ProtoReflect.Descriptor instead.
func (*TLMsgReadMentions) Descriptor() ([]byte, []int) {
	return file_msg_tl_proto_rawDescGZIP(), []int{16}
}

func (x *TLMsgReadMentions) GetConstructor() TLConstructor {
	if x != nil {
		return x.Constructor
	}
	return TLConstructor_CRC32_UNKNOWN
}

func (x *TLMsgReadMentions) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *TLMsgReadMentions) GetAuthKeyId() int64 {
	if x != nil {
		return x.AuthKeyId
	}
	return 0
}

func (x *TLMsgReadMentions) GetPeerType() int32 {
	if x != nil {
		return x.PeerType
	}
	return 0
}

func (x *TLMsgReadMentions) GetPeerId() int64 {
	if x != nil {
		return x.PeerId
	}
	return 0
}

func (x *TLMsgReadMentions) GetTopMsgId() *wrapperspb.Int32Value {
	if x != nil {
		return x.TopMsgId
	}
	return nil
}

// --------------------------------------------------------------------------------------------
type TLMsgUpdatePinnedMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Constructor   TLConstructor          `protobuf:"varint,1,opt,name=constructor,proto3,enum=msg.TLConstructor" json:"constructor,omitempty"`
	UserId        int64                  `protobuf:"varint,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	AuthKeyId     int64                  `protobuf:"varint,4,opt,name=auth_key_id,json=authKeyId,proto3" json:"auth_key_id,omitempty"`
	Silent        bool                   `protobuf:"varint,5,opt,name=silent,proto3" json:"silent,omitempty"`
	Unpin         bool                   `protobuf:"varint,6,opt,name=unpin,proto3" json:"unpin,omitempty"`
	PmOneside     bool                   `protobuf:"varint,7,opt,name=pm_oneside,json=pmOneside,proto3" json:"pm_oneside,omitempty"`
	PeerType      int32                  `protobuf:"varint,8,opt,name=peer_type,json=peerType,proto3" json:"peer_type,omitempty"`
	PeerId        int64                  `protobuf:"varint,9,opt,name=peer_id,json=peerId,proto3" json:"peer_id,omitempty"`
	Id            int32                  `protobuf:"varint,10,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TLMsgUpdatePinnedMessage) Reset() {
	*x = TLMsgUpdatePinnedMessage{}
	mi := &file_msg_tl_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TLMsgUpdatePinnedMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TLMsgUpdatePinnedMessage) ProtoMessage() {}

func (x *TLMsgUpdatePinnedMessage) ProtoReflect() protoreflect.Message {
	mi := &file_msg_tl_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TLMsgUpdatePinnedMessage.ProtoReflect.Descriptor instead.
func (*TLMsgUpdatePinnedMessage) Descriptor() ([]byte, []int) {
	return file_msg_tl_proto_rawDescGZIP(), []int{17}
}

func (x *TLMsgUpdatePinnedMessage) GetConstructor() TLConstructor {
	if x != nil {
		return x.Constructor
	}
	return TLConstructor_CRC32_UNKNOWN
}

func (x *TLMsgUpdatePinnedMessage) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *TLMsgUpdatePinnedMessage) GetAuthKeyId() int64 {
	if x != nil {
		return x.AuthKeyId
	}
	return 0
}

func (x *TLMsgUpdatePinnedMessage) GetSilent() bool {
	if x != nil {
		return x.Silent
	}
	return false
}

func (x *TLMsgUpdatePinnedMessage) GetUnpin() bool {
	if x != nil {
		return x.Unpin
	}
	return false
}

func (x *TLMsgUpdatePinnedMessage) GetPmOneside() bool {
	if x != nil {
		return x.PmOneside
	}
	return false
}

func (x *TLMsgUpdatePinnedMessage) GetPeerType() int32 {
	if x != nil {
		return x.PeerType
	}
	return 0
}

func (x *TLMsgUpdatePinnedMessage) GetPeerId() int64 {
	if x != nil {
		return x.PeerId
	}
	return 0
}

func (x *TLMsgUpdatePinnedMessage) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

// --------------------------------------------------------------------------------------------
type TLMsgUnpinAllMessages struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Constructor   TLConstructor          `protobuf:"varint,1,opt,name=constructor,proto3,enum=msg.TLConstructor" json:"constructor,omitempty"`
	UserId        int64                  `protobuf:"varint,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	AuthKeyId     int64                  `protobuf:"varint,4,opt,name=auth_key_id,json=authKeyId,proto3" json:"auth_key_id,omitempty"`
	PeerType      int32                  `protobuf:"varint,5,opt,name=peer_type,json=peerType,proto3" json:"peer_type,omitempty"`
	PeerId        int64                  `protobuf:"varint,6,opt,name=peer_id,json=peerId,proto3" json:"peer_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TLMsgUnpinAllMessages) Reset() {
	*x = TLMsgUnpinAllMessages{}
	mi := &file_msg_tl_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TLMsgUnpinAllMessages) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TLMsgUnpinAllMessages) ProtoMessage() {}

func (x *TLMsgUnpinAllMessages) ProtoReflect() protoreflect.Message {
	mi := &file_msg_tl_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TLMsgUnpinAllMessages.ProtoReflect.Descriptor instead.
func (*TLMsgUnpinAllMessages) Descriptor() ([]byte, []int) {
	return file_msg_tl_proto_rawDescGZIP(), []int{18}
}

func (x *TLMsgUnpinAllMessages) GetConstructor() TLConstructor {
	if x != nil {
		return x.Constructor
	}
	return TLConstructor_CRC32_UNKNOWN
}

func (x *TLMsgUnpinAllMessages) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *TLMsgUnpinAllMessages) GetAuthKeyId() int64 {
	if x != nil {
		return x.AuthKeyId
	}
	return 0
}

func (x *TLMsgUnpinAllMessages) GetPeerType() int32 {
	if x != nil {
		return x.PeerType
	}
	return 0
}

func (x *TLMsgUnpinAllMessages) GetPeerId() int64 {
	if x != nil {
		return x.PeerId
	}
	return 0
}

var File_msg_tl_proto protoreflect.FileDescriptor

const file_msg_tl_proto_rawDesc = "" +
	"\n" +
	"\fmsg.tl.proto\x12\x03msg\x1a\x1egoogle/protobuf/wrappers.proto\x1a\x1aschema.tl.core_types.proto\x1a\x19schema.tl.transport.proto\x1a\x14schema.tl.sync.proto\"\xa8\x02\n" +
	"\x0eContentMessage\x12%\n" +
	"\x0epredicate_name\x18\x01 \x01(\tR\rpredicateName\x124\n" +
	"\vconstructor\x18\x02 \x01(\x0e2\x12.msg.TLConstructorR\vconstructor\x12\x0e\n" +
	"\x02id\x18\x03 \x01(\x05R\x02id\x12*\n" +
	"\x11dialog_message_id\x18\x04 \x01(\x03R\x0fdialogMessageId\x12\x1c\n" +
	"\tmentioned\x18\x05 \x01(\bR\tmentioned\x12!\n" +
	"\fmedia_unread\x18\x06 \x01(\bR\vmediaUnread\x12\x1a\n" +
	"\breaction\x18\a \x01(\bR\breaction\x12 \n" +
	"\fsend_user_id\x18\b \x01(\x03R\n" +
	"sendUserId\">\n" +
	"\x11TL_contentMessage\x12)\n" +
	"\x05data2\x18\x01 \x01(\v2\x13.msg.ContentMessageR\x05data2\"\xb6\x02\n" +
	"\rOutboxMessage\x12%\n" +
	"\x0epredicate_name\x18\x01 \x01(\tR\rpredicateName\x124\n" +
	"\vconstructor\x18\x02 \x01(\x0e2\x12.msg.TLConstructorR\vconstructor\x12\x1d\n" +
	"\n" +
	"no_webpage\x18\x03 \x01(\bR\tnoWebpage\x12\x1e\n" +
	"\n" +
	"background\x18\x04 \x01(\bR\n" +
	"background\x12\x1b\n" +
	"\trandom_id\x18\x05 \x01(\x03R\brandomId\x12*\n" +
	"\amessage\x18\x06 \x01(\v2\x10.mtproto.MessageR\amessage\x12@\n" +
	"\rschedule_date\x18\a \x01(\v2\x1b.google.protobuf.Int32ValueR\fscheduleDate\"<\n" +
	"\x10TL_outboxMessage\x12(\n" +
	"\x05data2\x18\x01 \x01(\v2\x12.msg.OutboxMessageR\x05data2\"\xb2\x01\n" +
	"\x06Sender\x12%\n" +
	"\x0epredicate_name\x18\x01 \x01(\tR\rpredicateName\x124\n" +
	"\vconstructor\x18\x02 \x01(\x0e2\x12.msg.TLConstructorR\vconstructor\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\x03R\x06userId\x12\x12\n" +
	"\x04type\x18\x04 \x01(\x05R\x04type\x12\x1e\n" +
	"\vauth_key_id\x18\x05 \x01(\x03R\tauthKeyId\".\n" +
	"\tTL_sender\x12!\n" +
	"\x05data2\x18\x01 \x01(\v2\v.msg.SenderR\x05data2\"\x88\x02\n" +
	"\x16TL_msg_pushUserMessage\x124\n" +
	"\vconstructor\x18\x01 \x01(\x0e2\x12.msg.TLConstructorR\vconstructor\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\x03R\x06userId\x12\x1e\n" +
	"\vauth_key_id\x18\x04 \x01(\x03R\tauthKeyId\x12\x1b\n" +
	"\tpeer_type\x18\x05 \x01(\x05R\bpeerType\x12\x17\n" +
	"\apeer_id\x18\x06 \x01(\x03R\x06peerId\x12\x1b\n" +
	"\tpush_type\x18\a \x01(\x05R\bpushType\x12,\n" +
	"\amessage\x18\b \x01(\v2\x12.msg.OutboxMessageR\amessage\"\xe6\x01\n" +
	"\x1aTL_msg_readMessageContents\x124\n" +
	"\vconstructor\x18\x01 \x01(\x0e2\x12.msg.TLConstructorR\vconstructor\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\x03R\x06userId\x12\x1e\n" +
	"\vauth_key_id\x18\x04 \x01(\x03R\tauthKeyId\x12\x1b\n" +
	"\tpeer_type\x18\x05 \x01(\x05R\bpeerType\x12\x17\n" +
	"\apeer_id\x18\x06 \x01(\x03R\x06peerId\x12#\n" +
	"\x02id\x18\a \x03(\v2\x13.msg.ContentMessageR\x02id\"\xe9\x01\n" +
	"\x14TL_msg_sendMessageV2\x124\n" +
	"\vconstructor\x18\x01 \x01(\x0e2\x12.msg.TLConstructorR\vconstructor\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\x03R\x06userId\x12\x1e\n" +
	"\vauth_key_id\x18\x04 \x01(\x03R\tauthKeyId\x12\x1b\n" +
	"\tpeer_type\x18\x05 \x01(\x05R\bpeerType\x12\x17\n" +
	"\apeer_id\x18\x06 \x01(\x03R\x06peerId\x12,\n" +
	"\amessage\x18\a \x03(\v2\x12.msg.OutboxMessageR\amessage\"\xc3\x02\n" +
	"\x14TL_msg_editMessageV2\x124\n" +
	"\vconstructor\x18\x01 \x01(\x0e2\x12.msg.TLConstructorR\vconstructor\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\x03R\x06userId\x12\x1e\n" +
	"\vauth_key_id\x18\x04 \x01(\x03R\tauthKeyId\x12\x1b\n" +
	"\tpeer_type\x18\x05 \x01(\x05R\bpeerType\x12\x17\n" +
	"\apeer_id\x18\x06 \x01(\x03R\x06peerId\x12\x1b\n" +
	"\tedit_type\x18\a \x01(\x05R\beditType\x123\n" +
	"\vnew_message\x18\b \x01(\v2\x12.msg.OutboxMessageR\n" +
	"newMessage\x124\n" +
	"\vdst_message\x18\t \x01(\v2\x13.mtproto.MessageBoxR\n" +
	"dstMessage\"\xe4\x01\n" +
	"\x15TL_msg_deleteMessages\x124\n" +
	"\vconstructor\x18\x01 \x01(\x0e2\x12.msg.TLConstructorR\vconstructor\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\x03R\x06userId\x12\x1e\n" +
	"\vauth_key_id\x18\x04 \x01(\x03R\tauthKeyId\x12\x1b\n" +
	"\tpeer_type\x18\x05 \x01(\x05R\bpeerType\x12\x17\n" +
	"\apeer_id\x18\x06 \x01(\x03R\x06peerId\x12\x16\n" +
	"\x06revoke\x18\a \x01(\bR\x06revoke\x12\x0e\n" +
	"\x02id\x18\b \x03(\x05R\x02id\"\x89\x02\n" +
	"\x14TL_msg_deleteHistory\x124\n" +
	"\vconstructor\x18\x01 \x01(\x0e2\x12.msg.TLConstructorR\vconstructor\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\x03R\x06userId\x12\x1e\n" +
	"\vauth_key_id\x18\x04 \x01(\x03R\tauthKeyId\x12\x1b\n" +
	"\tpeer_type\x18\x05 \x01(\x05R\bpeerType\x12\x17\n" +
	"\apeer_id\x18\x06 \x01(\x03R\x06peerId\x12\x1d\n" +
	"\n" +
	"just_clear\x18\a \x01(\bR\tjustClear\x12\x16\n" +
	"\x06revoke\x18\b \x01(\bR\x06revoke\x12\x15\n" +
	"\x06max_id\x18\t \x01(\x05R\x05maxId\"\xa6\x01\n" +
	"\x1dTL_msg_deletePhoneCallHistory\x124\n" +
	"\vconstructor\x18\x01 \x01(\x0e2\x12.msg.TLConstructorR\vconstructor\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\x03R\x06userId\x12\x1e\n" +
	"\vauth_key_id\x18\x04 \x01(\x03R\tauthKeyId\x12\x16\n" +
	"\x06revoke\x18\x05 \x01(\bR\x06revoke\"\x8f\x01\n" +
	"\x18TL_msg_deleteChatHistory\x124\n" +
	"\vconstructor\x18\x01 \x01(\x0e2\x12.msg.TLConstructorR\vconstructor\x12\x17\n" +
	"\achat_id\x18\x03 \x01(\x03R\x06chatId\x12$\n" +
	"\x0edelete_user_id\x18\x04 \x01(\x03R\fdeleteUserId\"\xd0\x01\n" +
	"\x12TL_msg_readHistory\x124\n" +
	"\vconstructor\x18\x01 \x01(\x0e2\x12.msg.TLConstructorR\vconstructor\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\x03R\x06userId\x12\x1e\n" +
	"\vauth_key_id\x18\x04 \x01(\x03R\tauthKeyId\x12\x1b\n" +
	"\tpeer_type\x18\x05 \x01(\x05R\bpeerType\x12\x17\n" +
	"\apeer_id\x18\x06 \x01(\x03R\x06peerId\x12\x15\n" +
	"\x06max_id\x18\a \x01(\x05R\x05maxId\"\xd2\x01\n" +
	"\x14TL_msg_readHistoryV2\x124\n" +
	"\vconstructor\x18\x01 \x01(\x0e2\x12.msg.TLConstructorR\vconstructor\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\x03R\x06userId\x12\x1e\n" +
	"\vauth_key_id\x18\x04 \x01(\x03R\tauthKeyId\x12\x1b\n" +
	"\tpeer_type\x18\x05 \x01(\x05R\bpeerType\x12\x17\n" +
	"\apeer_id\x18\x06 \x01(\x03R\x06peerId\x12\x15\n" +
	"\x06max_id\x18\a \x01(\x05R\x05maxId\"\xf5\x01\n" +
	"\x13TL_msg_readMentions\x124\n" +
	"\vconstructor\x18\x01 \x01(\x0e2\x12.msg.TLConstructorR\vconstructor\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\x03R\x06userId\x12\x1e\n" +
	"\vauth_key_id\x18\x04 \x01(\x03R\tauthKeyId\x12\x1b\n" +
	"\tpeer_type\x18\x05 \x01(\x05R\bpeerType\x12\x17\n" +
	"\apeer_id\x18\x06 \x01(\x03R\x06peerId\x129\n" +
	"\n" +
	"top_msg_id\x18\a \x01(\v2\x1b.google.protobuf.Int32ValueR\btopMsgId\"\x9e\x02\n" +
	"\x1aTL_msg_updatePinnedMessage\x124\n" +
	"\vconstructor\x18\x01 \x01(\x0e2\x12.msg.TLConstructorR\vconstructor\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\x03R\x06userId\x12\x1e\n" +
	"\vauth_key_id\x18\x04 \x01(\x03R\tauthKeyId\x12\x16\n" +
	"\x06silent\x18\x05 \x01(\bR\x06silent\x12\x14\n" +
	"\x05unpin\x18\x06 \x01(\bR\x05unpin\x12\x1d\n" +
	"\n" +
	"pm_oneside\x18\a \x01(\bR\tpmOneside\x12\x1b\n" +
	"\tpeer_type\x18\b \x01(\x05R\bpeerType\x12\x17\n" +
	"\apeer_id\x18\t \x01(\x03R\x06peerId\x12\x0e\n" +
	"\x02id\x18\n" +
	" \x01(\x05R\x02id\"\xbe\x01\n" +
	"\x17TL_msg_unpinAllMessages\x124\n" +
	"\vconstructor\x18\x01 \x01(\x0e2\x12.msg.TLConstructorR\vconstructor\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\x03R\x06userId\x12\x1e\n" +
	"\vauth_key_id\x18\x04 \x01(\x03R\tauthKeyId\x12\x1b\n" +
	"\tpeer_type\x18\x05 \x01(\x05R\bpeerType\x12\x17\n" +
	"\apeer_id\x18\x06 \x01(\x03R\x06peerId*\xd4\x04\n" +
	"\rTLConstructor\x12\x11\n" +
	"\rCRC32_UNKNOWN\x10\x00\x12\x14\n" +
	"\fCRC32_sender\x10\xba\xc9\xe1\xd1\x05\x12\x1b\n" +
	"\x13CRC32_outboxMessage\x10\xb1\xc9Ԝ\x05\x12!\n" +
	"\x14CRC32_contentMessage\x10\xb3\xe2\x92\xeb\xf8\xff\xff\xff\xff\x01\x12!\n" +
	"\x19CRC32_msg_pushUserMessage\x10\x9a\xf4î\x03\x12%\n" +
	"\x1dCRC32_msg_readMessageContents\x10ԉ\x92\xc1\x02\x12$\n" +
	"\x17CRC32_msg_sendMessageV2\x10\xc4\xf9\xa9\xa6\xff\xff\xff\xff\xff\x01\x12\x1f\n" +
	"\x17CRC32_msg_editMessageV2\x10\xe1\xbf\xf9\xcf\x06\x12 \n" +
	"\x18CRC32_msg_deleteMessages\x10\x9d\x94\xa0\x8f\x02\x12\x1f\n" +
	"\x17CRC32_msg_deleteHistory\x10\xcaу\xae\a\x12(\n" +
	" CRC32_msg_deletePhoneCallHistory\x10\xbe\xc2\u07b5\x02\x12(\n" +
	"\x1bCRC32_msg_deleteChatHistory\x10\xdb\xc5\xfd\xf8\xfe\xff\xff\xff\xff\x01\x12\x1d\n" +
	"\x15CRC32_msg_readHistory\x10\x92ܽ\xd0\x05\x12\x1e\n" +
	"\x16CRC32_msg_readMentions\x10\xc6Ƣ\x8b\x01\x12\x1e\n" +
	"\x17CRC32_msg_readHistoryV2\x10\x86\xe4\xe6}\x12*\n" +
	"\x1dCRC32_msg_updatePinnedMessage\x10\xa9\xa3\xb9\xad\xfe\xff\xff\xff\xff\x01\x12'\n" +
	"\x1aCRC32_msg_unpinAllMessages\x10\xa5\xbe\x99\xc4\xfb\xff\xff\xff\xff\x012\xc0\b\n" +
	"\x06RPCMsg\x12C\n" +
	"\x13msg_pushUserMessage\x12\x1b.msg.TL_msg_pushUserMessage\x1a\r.mtproto.Bool\"\x00\x12`\n" +
	"\x17msg_readMessageContents\x12\x1f.msg.TL_msg_readMessageContents\x1a\".mtproto.messages_AffectedMessages\"\x00\x12B\n" +
	"\x11msg_sendMessageV2\x12\x19.msg.TL_msg_sendMessageV2\x1a\x10.mtproto.Updates\"\x00\x12B\n" +
	"\x11msg_editMessageV2\x12\x19.msg.TL_msg_editMessageV2\x1a\x10.mtproto.Updates\"\x00\x12V\n" +
	"\x12msg_deleteMessages\x12\x1a.msg.TL_msg_deleteMessages\x1a\".mtproto.messages_AffectedMessages\"\x00\x12S\n" +
	"\x11msg_deleteHistory\x12\x19.msg.TL_msg_deleteHistory\x1a!.mtproto.messages_AffectedHistory\"\x00\x12k\n" +
	"\x1amsg_deletePhoneCallHistory\x12\".msg.TL_msg_deletePhoneCallHistory\x1a'.mtproto.messages_AffectedFoundMessages\"\x00\x12G\n" +
	"\x15msg_deleteChatHistory\x12\x1d.msg.TL_msg_deleteChatHistory\x1a\r.mtproto.Bool\"\x00\x12P\n" +
	"\x0fmsg_readHistory\x12\x17.msg.TL_msg_readHistory\x1a\".mtproto.messages_AffectedMessages\"\x00\x12T\n" +
	"\x11msg_readHistoryV2\x12\x19.msg.TL_msg_readHistoryV2\x1a\".mtproto.messages_AffectedMessages\"\x00\x12Q\n" +
	"\x10msg_readMentions\x12\x18.msg.TL_msg_readMentions\x1a!.mtproto.messages_AffectedHistory\"\x00\x12N\n" +
	"\x17msg_updatePinnedMessage\x12\x1f.msg.TL_msg_updatePinnedMessage\x1a\x10.mtproto.Updates\"\x00\x12Y\n" +
	"\x14msg_unpinAllMessages\x12\x1c.msg.TL_msg_unpinAllMessages\x1a!.mtproto.messages_AffectedHistory\"\x00B?Z=github.com/teamgram/teamgram-server/app/messenger/msg/msg/msgb\x06proto3"

var (
	file_msg_tl_proto_rawDescOnce sync.Once
	file_msg_tl_proto_rawDescData []byte
)

func file_msg_tl_proto_rawDescGZIP() []byte {
	file_msg_tl_proto_rawDescOnce.Do(func() {
		file_msg_tl_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_msg_tl_proto_rawDesc), len(file_msg_tl_proto_rawDesc)))
	})
	return file_msg_tl_proto_rawDescData
}

var file_msg_tl_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_msg_tl_proto_msgTypes = make([]protoimpl.MessageInfo, 19)
var file_msg_tl_proto_goTypes = []any{
	(TLConstructor)(0),                             // 0: msg.TLConstructor
	(*ContentMessage)(nil),                         // 1: msg.ContentMessage
	(*TLContentMessage)(nil),                       // 2: msg.TL_contentMessage
	(*OutboxMessage)(nil),                          // 3: msg.OutboxMessage
	(*TLOutboxMessage)(nil),                        // 4: msg.TL_outboxMessage
	(*Sender)(nil),                                 // 5: msg.Sender
	(*TLSender)(nil),                               // 6: msg.TL_sender
	(*TLMsgPushUserMessage)(nil),                   // 7: msg.TL_msg_pushUserMessage
	(*TLMsgReadMessageContents)(nil),               // 8: msg.TL_msg_readMessageContents
	(*TLMsgSendMessageV2)(nil),                     // 9: msg.TL_msg_sendMessageV2
	(*TLMsgEditMessageV2)(nil),                     // 10: msg.TL_msg_editMessageV2
	(*TLMsgDeleteMessages)(nil),                    // 11: msg.TL_msg_deleteMessages
	(*TLMsgDeleteHistory)(nil),                     // 12: msg.TL_msg_deleteHistory
	(*TLMsgDeletePhoneCallHistory)(nil),            // 13: msg.TL_msg_deletePhoneCallHistory
	(*TLMsgDeleteChatHistory)(nil),                 // 14: msg.TL_msg_deleteChatHistory
	(*TLMsgReadHistory)(nil),                       // 15: msg.TL_msg_readHistory
	(*TLMsgReadHistoryV2)(nil),                     // 16: msg.TL_msg_readHistoryV2
	(*TLMsgReadMentions)(nil),                      // 17: msg.TL_msg_readMentions
	(*TLMsgUpdatePinnedMessage)(nil),               // 18: msg.TL_msg_updatePinnedMessage
	(*TLMsgUnpinAllMessages)(nil),                  // 19: msg.TL_msg_unpinAllMessages
	(*mtproto.Message)(nil),                        // 20: mtproto.Message
	(*wrapperspb.Int32Value)(nil),                  // 21: google.protobuf.Int32Value
	(*mtproto.MessageBox)(nil),                     // 22: mtproto.MessageBox
	(*mtproto.Bool)(nil),                           // 23: mtproto.Bool
	(*mtproto.Messages_AffectedMessages)(nil),      // 24: mtproto.messages_AffectedMessages
	(*mtproto.Updates)(nil),                        // 25: mtproto.Updates
	(*mtproto.Messages_AffectedHistory)(nil),       // 26: mtproto.messages_AffectedHistory
	(*mtproto.Messages_AffectedFoundMessages)(nil), // 27: mtproto.messages_AffectedFoundMessages
}
var file_msg_tl_proto_depIdxs = []int32{
	0,  // 0: msg.ContentMessage.constructor:type_name -> msg.TLConstructor
	1,  // 1: msg.TL_contentMessage.data2:type_name -> msg.ContentMessage
	0,  // 2: msg.OutboxMessage.constructor:type_name -> msg.TLConstructor
	20, // 3: msg.OutboxMessage.message:type_name -> mtproto.Message
	21, // 4: msg.OutboxMessage.schedule_date:type_name -> google.protobuf.Int32Value
	3,  // 5: msg.TL_outboxMessage.data2:type_name -> msg.OutboxMessage
	0,  // 6: msg.Sender.constructor:type_name -> msg.TLConstructor
	5,  // 7: msg.TL_sender.data2:type_name -> msg.Sender
	0,  // 8: msg.TL_msg_pushUserMessage.constructor:type_name -> msg.TLConstructor
	3,  // 9: msg.TL_msg_pushUserMessage.message:type_name -> msg.OutboxMessage
	0,  // 10: msg.TL_msg_readMessageContents.constructor:type_name -> msg.TLConstructor
	1,  // 11: msg.TL_msg_readMessageContents.id:type_name -> msg.ContentMessage
	0,  // 12: msg.TL_msg_sendMessageV2.constructor:type_name -> msg.TLConstructor
	3,  // 13: msg.TL_msg_sendMessageV2.message:type_name -> msg.OutboxMessage
	0,  // 14: msg.TL_msg_editMessageV2.constructor:type_name -> msg.TLConstructor
	3,  // 15: msg.TL_msg_editMessageV2.new_message:type_name -> msg.OutboxMessage
	22, // 16: msg.TL_msg_editMessageV2.dst_message:type_name -> mtproto.MessageBox
	0,  // 17: msg.TL_msg_deleteMessages.constructor:type_name -> msg.TLConstructor
	0,  // 18: msg.TL_msg_deleteHistory.constructor:type_name -> msg.TLConstructor
	0,  // 19: msg.TL_msg_deletePhoneCallHistory.constructor:type_name -> msg.TLConstructor
	0,  // 20: msg.TL_msg_deleteChatHistory.constructor:type_name -> msg.TLConstructor
	0,  // 21: msg.TL_msg_readHistory.constructor:type_name -> msg.TLConstructor
	0,  // 22: msg.TL_msg_readHistoryV2.constructor:type_name -> msg.TLConstructor
	0,  // 23: msg.TL_msg_readMentions.constructor:type_name -> msg.TLConstructor
	21, // 24: msg.TL_msg_readMentions.top_msg_id:type_name -> google.protobuf.Int32Value
	0,  // 25: msg.TL_msg_updatePinnedMessage.constructor:type_name -> msg.TLConstructor
	0,  // 26: msg.TL_msg_unpinAllMessages.constructor:type_name -> msg.TLConstructor
	7,  // 27: msg.RPCMsg.msg_pushUserMessage:input_type -> msg.TL_msg_pushUserMessage
	8,  // 28: msg.RPCMsg.msg_readMessageContents:input_type -> msg.TL_msg_readMessageContents
	9,  // 29: msg.RPCMsg.msg_sendMessageV2:input_type -> msg.TL_msg_sendMessageV2
	10, // 30: msg.RPCMsg.msg_editMessageV2:input_type -> msg.TL_msg_editMessageV2
	11, // 31: msg.RPCMsg.msg_deleteMessages:input_type -> msg.TL_msg_deleteMessages
	12, // 32: msg.RPCMsg.msg_deleteHistory:input_type -> msg.TL_msg_deleteHistory
	13, // 33: msg.RPCMsg.msg_deletePhoneCallHistory:input_type -> msg.TL_msg_deletePhoneCallHistory
	14, // 34: msg.RPCMsg.msg_deleteChatHistory:input_type -> msg.TL_msg_deleteChatHistory
	15, // 35: msg.RPCMsg.msg_readHistory:input_type -> msg.TL_msg_readHistory
	16, // 36: msg.RPCMsg.msg_readHistoryV2:input_type -> msg.TL_msg_readHistoryV2
	17, // 37: msg.RPCMsg.msg_readMentions:input_type -> msg.TL_msg_readMentions
	18, // 38: msg.RPCMsg.msg_updatePinnedMessage:input_type -> msg.TL_msg_updatePinnedMessage
	19, // 39: msg.RPCMsg.msg_unpinAllMessages:input_type -> msg.TL_msg_unpinAllMessages
	23, // 40: msg.RPCMsg.msg_pushUserMessage:output_type -> mtproto.Bool
	24, // 41: msg.RPCMsg.msg_readMessageContents:output_type -> mtproto.messages_AffectedMessages
	25, // 42: msg.RPCMsg.msg_sendMessageV2:output_type -> mtproto.Updates
	25, // 43: msg.RPCMsg.msg_editMessageV2:output_type -> mtproto.Updates
	24, // 44: msg.RPCMsg.msg_deleteMessages:output_type -> mtproto.messages_AffectedMessages
	26, // 45: msg.RPCMsg.msg_deleteHistory:output_type -> mtproto.messages_AffectedHistory
	27, // 46: msg.RPCMsg.msg_deletePhoneCallHistory:output_type -> mtproto.messages_AffectedFoundMessages
	23, // 47: msg.RPCMsg.msg_deleteChatHistory:output_type -> mtproto.Bool
	24, // 48: msg.RPCMsg.msg_readHistory:output_type -> mtproto.messages_AffectedMessages
	24, // 49: msg.RPCMsg.msg_readHistoryV2:output_type -> mtproto.messages_AffectedMessages
	26, // 50: msg.RPCMsg.msg_readMentions:output_type -> mtproto.messages_AffectedHistory
	25, // 51: msg.RPCMsg.msg_updatePinnedMessage:output_type -> mtproto.Updates
	26, // 52: msg.RPCMsg.msg_unpinAllMessages:output_type -> mtproto.messages_AffectedHistory
	40, // [40:53] is the sub-list for method output_type
	27, // [27:40] is the sub-list for method input_type
	27, // [27:27] is the sub-list for extension type_name
	27, // [27:27] is the sub-list for extension extendee
	0,  // [0:27] is the sub-list for field type_name
}

func init() { file_msg_tl_proto_init() }
func file_msg_tl_proto_init() {
	if File_msg_tl_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_msg_tl_proto_rawDesc), len(file_msg_tl_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   19,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_msg_tl_proto_goTypes,
		DependencyIndexes: file_msg_tl_proto_depIdxs,
		EnumInfos:         file_msg_tl_proto_enumTypes,
		MessageInfos:      file_msg_tl_proto_msgTypes,
	}.Build()
	File_msg_tl_proto = out.File
	file_msg_tl_proto_goTypes = nil
	file_msg_tl_proto_depIdxs = nil
}
