services:
  backend:
    image: teamgram-server-latest:20261006-r16-prod
    build: !reset null
    volumes:
      - /Users/mac/open/test/teamgram-server/docker/production/bff.production.yaml:/app/etc2/bff.yaml:ro
