package persist

import (
	"database/sql"
	"encoding/json"
	"errors"
	"fmt"
	"strings"
	"time"
)

func ensureMiniBotAppSchema(db *sql.DB) error {
	for _, statement := range []string{
		`CREATE TABLE IF NOT EXISTS apifull_mini_bot_permission (
			user_id BIGINT NOT NULL,
			bot_id BIGINT NOT NULL,
			can_send BOOLEAN NOT NULL DEFAULT FALSE,
			updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
			PRIMARY KEY (user_id, bot_id)
		)`,
		`CREATE INDEX IF NOT EXISTS idx_apifull_mini_bot_permission_bot
			ON apifull_mini_bot_permission (bot_id, user_id)`,
		`CREATE TABLE IF NOT EXISTS apifull_webview_request (
			request_id VARCHAR(128) PRIMARY KEY,
			user_id BIGINT NOT NULL,
			bot_id BIGINT NOT NULL,
			kind VARCHAR(64) NOT NULL,
			payload JSONB NOT NULL DEFAULT '{}'::jsonb,
			expires_at TIMESTAMPTZ NOT NULL,
			created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
			updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
		)`,
		`CREATE INDEX IF NOT EXISTS idx_apifull_webview_request_owner
			ON apifull_webview_request (user_id, bot_id, kind, updated_at DESC)`,
		`CREATE INDEX IF NOT EXISTS idx_apifull_webview_request_expiry
			ON apifull_webview_request (expires_at)`,
	} {
		if _, err := db.Exec(statement); err != nil {
			return err
		}
	}
	return nil
}

// ErrMiniBotStateUnavailable is returned when a Mini App operation is
// attempted without the deployment-owned PostgreSQL store.
var ErrMiniBotStateUnavailable = errors.New("apifull: Mini App state requires PostgreSQL")

// WebViewRequest is the durable portion of a Layer 229 WebView request. The
// payload is intentionally opaque to the persistence package; the API layer
// owns the TL-specific shape and validates it before writing.
type WebViewRequest struct {
	RequestID string
	UserID    int64
	BotID     int64
	Kind      string
	Payload   string
	ExpiresAt time.Time
}

func miniBotStore() (*postgresStore, error) {
	store, ok := Default.(*postgresStore)
	if !ok || store == nil || store.db == nil {
		return nil, ErrMiniBotStateUnavailable
	}
	return store, nil
}

// GetMiniBotPermission reads the current user -> bot write permission. An
// absent row is the Telegram default (false), not an error.
func GetMiniBotPermission(userID, botID int64) (bool, error) {
	store, err := miniBotStore()
	if err != nil {
		return false, err
	}
	var allowed bool
	err = store.db.QueryRow(`SELECT can_send FROM apifull_mini_bot_permission
		WHERE user_id = $1 AND bot_id = $2`, userID, botID).Scan(&allowed)
	if err == sql.ErrNoRows {
		return false, nil
	}
	return allowed, err
}

// SetMiniBotPermission changes the user -> bot write permission in one
// transaction. The advisory lock closes the absent-row race between workers.
func SetMiniBotPermission(userID, botID int64, allowed bool) error {
	store, err := miniBotStore()
	if err != nil {
		return err
	}
	tx, err := store.db.Begin()
	if err != nil {
		return err
	}
	defer func() { _ = tx.Rollback() }()
	if _, err = tx.Exec(`SELECT pg_advisory_xact_lock(hashtextextended($1, 0))`,
		fmt.Sprintf("apifull-mini-bot-permission:%d:%d", userID, botID)); err != nil {
		return err
	}
	_, err = tx.Exec(`INSERT INTO apifull_mini_bot_permission(user_id, bot_id, can_send, updated_at)
		VALUES ($1, $2, $3, CURRENT_TIMESTAMP)
		ON CONFLICT (user_id, bot_id) DO UPDATE SET can_send = EXCLUDED.can_send,
		updated_at = CURRENT_TIMESTAMP`, userID, botID, allowed)
	if err != nil {
		return err
	}
	return tx.Commit()
}

// PutWebViewRequest atomically records one WebView request. Request IDs are
// generated by the API layer and are opaque to PostgreSQL.
func PutWebViewRequest(request WebViewRequest) error {
	store, err := miniBotStore()
	if err != nil {
		return err
	}
	if strings.TrimSpace(request.RequestID) == "" || request.UserID <= 0 || request.BotID <= 0 || strings.TrimSpace(request.Kind) == "" {
		return errors.New("apifull: invalid WebView request identity")
	}
	if !json.Valid([]byte(request.Payload)) {
		return errors.New("apifull: WebView request payload must be JSON")
	}
	if request.ExpiresAt.IsZero() {
		return errors.New("apifull: WebView request expiry is required")
	}
	_, err = store.db.Exec(`INSERT INTO apifull_webview_request
		(request_id, user_id, bot_id, kind, payload, expires_at, created_at, updated_at)
		VALUES ($1, $2, $3, $4, $5::jsonb, $6, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
		ON CONFLICT (request_id) DO UPDATE SET user_id = EXCLUDED.user_id,
		bot_id = EXCLUDED.bot_id, kind = EXCLUDED.kind, payload = EXCLUDED.payload,
		expires_at = EXCLUDED.expires_at, updated_at = CURRENT_TIMESTAMP`,
		request.RequestID, request.UserID, request.BotID, request.Kind, request.Payload, request.ExpiresAt.UTC())
	return err
}

// GetWebViewRequest loads an unexpired request owned by userID. Expired rows
// are intentionally retained for auditability and are never returned.
func GetWebViewRequest(userID int64, requestID string) (*WebViewRequest, error) {
	store, err := miniBotStore()
	if err != nil {
		return nil, err
	}
	var request WebViewRequest
	err = store.db.QueryRow(`SELECT request_id, user_id, bot_id, kind, payload, expires_at
		FROM apifull_webview_request
		WHERE request_id = $1 AND user_id = $2 AND expires_at > CURRENT_TIMESTAMP`, requestID, userID).
		Scan(&request.RequestID, &request.UserID, &request.BotID, &request.Kind, &request.Payload, &request.ExpiresAt)
	if err == sql.ErrNoRows {
		return nil, nil
	}
	if err != nil {
		return nil, err
	}
	return &request, nil
}

// ProlongWebViewRequest extends an unexpired request under a row lock and
// returns false when it is missing or already expired.
func ProlongWebViewRequest(userID int64, requestID string, ttl time.Duration) (bool, error) {
	store, err := miniBotStore()
	if err != nil {
		return false, err
	}
	if ttl <= 0 {
		return false, errors.New("apifull: WebView request TTL must be positive")
	}
	tx, err := store.db.Begin()
	if err != nil {
		return false, err
	}
	defer func() { _ = tx.Rollback() }()
	var expires time.Time
	err = tx.QueryRow(`SELECT expires_at FROM apifull_webview_request
		WHERE request_id = $1 AND user_id = $2 FOR UPDATE`, requestID, userID).Scan(&expires)
	if err == sql.ErrNoRows || !expires.After(time.Now().UTC()) {
		return false, nil
	}
	if _, err = tx.Exec(`UPDATE apifull_webview_request SET expires_at = CURRENT_TIMESTAMP + $1::interval,
		updated_at = CURRENT_TIMESTAMP WHERE request_id = $2 AND user_id = $3`,
		fmt.Sprintf("%d seconds", int64(ttl/time.Second)), requestID, userID); err != nil {
		return false, err
	}
	if err = tx.Commit(); err != nil {
		return false, err
	}
	return true, nil
}

// ProlongWebViewQuery extends the request identified by its Telegram query
// id. The API layer stores query_id in the JSON payload because the wire
// method exposes that value rather than the internal request id.
func ProlongWebViewQuery(userID, queryID int64, ttl time.Duration) (bool, error) {
	store, err := miniBotStore()
	if err != nil {
		return false, err
	}
	if queryID <= 0 || ttl <= 0 {
		return false, errors.New("apifull: invalid WebView query or TTL")
	}
	tx, err := store.db.Begin()
	if err != nil {
		return false, err
	}
	defer func() { _ = tx.Rollback() }()
	var expires time.Time
	err = tx.QueryRow(`SELECT expires_at FROM apifull_webview_request
		WHERE user_id = $1 AND payload->>'query_id' = $2 AND expires_at > CURRENT_TIMESTAMP
		ORDER BY updated_at DESC LIMIT 1 FOR UPDATE`, userID, fmt.Sprintf("%d", queryID)).Scan(&expires)
	if err == sql.ErrNoRows {
		return false, nil
	}
	if err != nil {
		return false, err
	}
	if _, err = tx.Exec(`UPDATE apifull_webview_request SET expires_at = CURRENT_TIMESTAMP + $1::interval,
		updated_at = CURRENT_TIMESTAMP WHERE user_id = $2 AND payload->>'query_id' = $3
		AND expires_at > CURRENT_TIMESTAMP`, fmt.Sprintf("%d seconds", int64(ttl/time.Second)), userID, fmt.Sprintf("%d", queryID)); err != nil {
		return false, err
	}
	if err = tx.Commit(); err != nil {
		return false, err
	}
	return true, nil
}
