package postgres_dao

import (
	"context"
	"crypto/sha256"
	"fmt"
	"os"
	"strings"
	"testing"
	"time"

	"github.com/jackc/pgx/v5/pgxpool"
	"github.com/teamgram/teamgram-server/app/service/media/internal/dal/dataobject"
)

func TestDocumentsSelectByHashPostgres18(t *testing.T) {
	dsn := os.Getenv("MEDIA_POSTGRES_DSN")
	if dsn == "" {
		dsn = os.Getenv("TEAMGRAM_POSTGRES_DSN")
	}
	if dsn == "" {
		t.Skip("MEDIA_POSTGRES_DSN must point to an isolated PostgreSQL 18 database")
	}

	ctx := context.Background()
	admin, err := pgxpool.New(ctx, dsn)
	if err != nil {
		t.Fatal(err)
	}
	defer admin.Close()
	var version int
	if err = admin.QueryRow(ctx, `SELECT current_setting('server_version_num')::INTEGER`).Scan(&version); err != nil {
		t.Fatal(err)
	}
	if version < 180000 || version >= 190000 {
		t.Fatalf("PostgreSQL server_version_num = %d, want 18.x", version)
	}

	schema := fmt.Sprintf("media_hash_test_%d_%d", os.Getpid(), time.Now().UnixNano())
	if _, err = admin.Exec(ctx, `CREATE SCHEMA `+schema); err != nil {
		t.Fatal(err)
	}
	t.Cleanup(func() {
		admin.Exec(context.Background(), `DROP SCHEMA `+schema+` CASCADE`)
	})

	poolConfig, err := pgxpool.ParseConfig(dsn)
	if err != nil {
		t.Fatal(err)
	}
	poolConfig.ConnConfig.RuntimeParams["search_path"] = schema
	pool, err := pgxpool.NewWithConfig(ctx, poolConfig)
	if err != nil {
		t.Fatal(err)
	}
	defer pool.Close()
	if _, err = pool.Exec(ctx, `CREATE TABLE documents (
		id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
		document_id BIGINT NOT NULL UNIQUE,
		access_hash BIGINT NOT NULL,
		dc_id INTEGER NOT NULL,
		file_path TEXT NOT NULL,
		file_size BIGINT NOT NULL DEFAULT 0,
		uploaded_file_name TEXT NOT NULL DEFAULT '',
		ext TEXT NOT NULL DEFAULT '',
		mime_type TEXT NOT NULL DEFAULT '',
		sha256 BYTEA NOT NULL DEFAULT ''::bytea,
		thumb_id BIGINT NOT NULL DEFAULT 0,
		video_thumb_id BIGINT NOT NULL DEFAULT 0,
		attributes JSONB NOT NULL DEFAULT '{}'::jsonb,
		version INTEGER NOT NULL DEFAULT 0,
		date2 BIGINT NOT NULL DEFAULT 0,
		import_document_id BIGINT NOT NULL DEFAULT 0,
		deleted BOOLEAN NOT NULL DEFAULT FALSE
	)`); err != nil {
		t.Fatal(err)
	}
	if _, err = pool.Exec(ctx, `CREATE INDEX documents_sha256_lookup_idx
		ON documents (sha256, file_size, mime_type, id)
		WHERE deleted = FALSE AND octet_length(sha256) = 32`); err != nil {
		t.Fatal(err)
	}
	dao := NewDocumentsDAO(pool)
	hash := sha256.Sum256([]byte("document content"))
	insert := func(documentID int64) int64 {
		t.Helper()
		id, _, insertErr := dao.Insert(ctx, &dataobject.DocumentsDO{
			DocumentId: documentID,
			AccessHash: documentID + 100,
			FilePath:   fmt.Sprintf("%d.dat", documentID),
			FileSize:   int64(len("document content")),
			MimeType:   "application/octet-stream",
			Sha256:     hash[:],
		})
		if insertErr != nil {
			t.Fatal(insertErr)
		}
		return id
	}
	deletedID := insert(501)
	if _, err = pool.Exec(ctx, `UPDATE documents SET deleted = TRUE WHERE id = $1`, deletedID); err != nil {
		t.Fatal(err)
	}
	wantID := insert(502)
	insert(503)

	conn, err := pool.Acquire(ctx)
	if err != nil {
		t.Fatal(err)
	}
	defer conn.Release()
	if _, err = conn.Exec(ctx, `SET enable_seqscan = OFF`); err != nil {
		t.Fatal(err)
	}
	plans, err := conn.Query(ctx, `EXPLAIN SELECT id FROM documents
		WHERE sha256 = $1 AND file_size = $2 AND mime_type = $3 AND deleted = FALSE
		  AND octet_length(sha256) = 32
		ORDER BY id LIMIT 1`, hash[:], int64(len("document content")), "application/octet-stream")
	if err != nil {
		t.Fatal(err)
	}
	var plan string
	usesHashIndex := false
	for plans.Next() {
		if err = plans.Scan(&plan); err != nil {
			plans.Close()
			t.Fatal(err)
		}
		usesHashIndex = usesHashIndex || strings.Contains(plan, "documents_sha256_lookup_idx")
	}
	if err = plans.Err(); err != nil {
		plans.Close()
		t.Fatal(err)
	}
	plans.Close()
	if !usesHashIndex {
		t.Fatal("hash lookup plan does not use documents_sha256_lookup_idx")
	}

	got, err := dao.SelectByHash(ctx, hash[:], int64(len("document content")), "application/octet-stream")
	if err != nil {
		t.Fatal(err)
	}
	if got == nil || got.Id != wantID || got.DocumentId != 502 || string(got.Sha256) != string(hash[:]) {
		t.Fatalf("SelectByHash() = %+v, want first active matching document %d", got, wantID)
	}
	for _, tc := range []struct {
		name     string
		hash     []byte
		size     int64
		mimeType string
	}{
		{name: "hash mismatch", hash: make([]byte, sha256.Size), size: int64(len("document content")), mimeType: "application/octet-stream"},
		{name: "size mismatch", hash: hash[:], size: 1, mimeType: "application/octet-stream"},
		{name: "mime mismatch", hash: hash[:], size: int64(len("document content")), mimeType: "image/png"},
	} {
		t.Run(tc.name, func(t *testing.T) {
			got, err := dao.SelectByHash(ctx, tc.hash, tc.size, tc.mimeType)
			if err != nil || got != nil {
				t.Fatalf("SelectByHash() = (%+v, %v), want (nil, nil)", got, err)
			}
		})
	}
}
