-- PostgreSQL 18 schema for the authsession service.
--
-- This is a fresh-install schema. It intentionally does not contain ALTER
-- statements for the historical MySQL schema: the project has not launched,
-- so the PostgreSQL database is created from the current model directly.

CREATE TABLE IF NOT EXISTS auths (
    -- BY DEFAULT keeps normal inserts sequence-backed while allowing the
    -- existing test/bootstrap DAO to provide a deterministic id explicitly.
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    auth_key_id BIGINT NOT NULL,
    layer INTEGER NOT NULL DEFAULT 0,
    api_id INTEGER NOT NULL DEFAULT 0,
    device_model TEXT NOT NULL DEFAULT '',
    system_version TEXT NOT NULL DEFAULT '',
    app_version TEXT NOT NULL DEFAULT '',
    system_lang_code TEXT NOT NULL DEFAULT '',
    lang_pack TEXT NOT NULL DEFAULT '',
    lang_code TEXT NOT NULL DEFAULT '',
    system_code TEXT NOT NULL DEFAULT '',
    proxy TEXT NOT NULL DEFAULT '',
    params JSONB NOT NULL DEFAULT 'null'::jsonb,
    client_ip INET,
    date_active BIGINT NOT NULL DEFAULT 0,
    deleted BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT auths_auth_key_id_key UNIQUE (auth_key_id)
);

CREATE INDEX IF NOT EXISTS auths_active_idx
    ON auths (auth_key_id) WHERE deleted = FALSE;

CREATE TABLE IF NOT EXISTS auth_keys (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    auth_key_id BIGINT NOT NULL,
    -- MTProto auth keys are binary values. Keeping them as bytea avoids the
    -- base64 expansion used by the old MySQL schema.
    body BYTEA NOT NULL,
    deleted BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT auth_keys_auth_key_id_key UNIQUE (auth_key_id)
);

CREATE TABLE IF NOT EXISTS auth_key_infos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    auth_key_id BIGINT NOT NULL,
    auth_key_type INTEGER NOT NULL DEFAULT 0,
    perm_auth_key_id BIGINT NOT NULL DEFAULT 0,
    temp_auth_key_id BIGINT NOT NULL DEFAULT 0,
    media_temp_auth_key_id BIGINT NOT NULL DEFAULT 0,
    deleted BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT auth_key_infos_auth_key_id_key UNIQUE (auth_key_id)
);

CREATE TABLE IF NOT EXISTS auth_users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    auth_key_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL DEFAULT 0,
    hash BIGINT NOT NULL DEFAULT 0,
    date_created BIGINT NOT NULL DEFAULT 0,
    date_active BIGINT NOT NULL DEFAULT 0,
    state INTEGER NOT NULL DEFAULT 0,
    android_push_session_id BIGINT NOT NULL DEFAULT 0,
    deleted BOOLEAN NOT NULL DEFAULT FALSE,
    -- A deleted row releases the auth key so a new owner can bind it. The
    -- partial unique index below enforces the same invariant without relying
    -- on nullable generated columns.
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE UNIQUE INDEX IF NOT EXISTS auth_users_active_auth_key_id_key
    ON auth_users (auth_key_id) WHERE deleted = FALSE;

CREATE INDEX IF NOT EXISTS auth_users_user_id_active_idx
    ON auth_users (user_id, id) WHERE deleted = FALSE;

CREATE INDEX IF NOT EXISTS auth_users_auth_key_id_active_idx
    ON auth_users (auth_key_id) WHERE deleted = FALSE;

-- Keep update timestamps correct without requiring every caller to assign
-- updated_at explicitly. This trigger is local to the authsession tables.
CREATE OR REPLACE FUNCTION authsession_set_updated_at()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
    NEW.updated_at = CURRENT_TIMESTAMP;
    RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS auths_set_updated_at ON auths;
CREATE TRIGGER auths_set_updated_at
    BEFORE UPDATE ON auths
    FOR EACH ROW EXECUTE FUNCTION authsession_set_updated_at();

DROP TRIGGER IF EXISTS auth_key_infos_set_updated_at ON auth_key_infos;
CREATE TRIGGER auth_key_infos_set_updated_at
    BEFORE UPDATE ON auth_key_infos
    FOR EACH ROW EXECUTE FUNCTION authsession_set_updated_at();

DROP TRIGGER IF EXISTS auth_users_set_updated_at ON auth_users;
CREATE TRIGGER auth_users_set_updated_at
    BEFORE UPDATE ON auth_users
    FOR EACH ROW EXECUTE FUNCTION authsession_set_updated_at();
