-- PostgreSQL 18 schema for the basic-group chat service.
--
-- This is a fresh-install schema. IDs use PostgreSQL identity sequences and
-- booleans use PostgreSQL boolean values instead of integer flags.

CREATE TABLE IF NOT EXISTS chats (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    creator_user_id BIGINT NOT NULL,
    access_hash BIGINT NOT NULL,
    random_id BIGINT NOT NULL,
    participant_count INTEGER NOT NULL DEFAULT 0,
    title TEXT NOT NULL DEFAULT '',
    about TEXT NOT NULL DEFAULT '',
    photo_id BIGINT NOT NULL DEFAULT 0,
    default_banned_rights BIGINT NOT NULL DEFAULT 0,
    migrated_to_id BIGINT NOT NULL DEFAULT 0,
    migrated_to_access_hash BIGINT NOT NULL DEFAULT 0,
    available_reactions_type INTEGER NOT NULL DEFAULT 0,
    available_reactions TEXT NOT NULL DEFAULT '',
    deactivated BOOLEAN NOT NULL DEFAULT FALSE,
    noforwards BOOLEAN NOT NULL DEFAULT FALSE,
    ttl_period INTEGER NOT NULL DEFAULT 0,
    version INTEGER NOT NULL DEFAULT 1,
    date BIGINT NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS chats_creator_date_idx
    ON chats (creator_user_id, date DESC, id DESC);
CREATE INDEX IF NOT EXISTS chats_title_search_idx
    ON chats (title text_pattern_ops);

CREATE TABLE IF NOT EXISTS chat_participants (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    chat_id BIGINT NOT NULL REFERENCES chats(id) ON DELETE CASCADE,
    user_id BIGINT NOT NULL,
    participant_type INTEGER NOT NULL DEFAULT 0,
    link TEXT NOT NULL DEFAULT '',
    usage2 INTEGER NOT NULL DEFAULT 0,
    admin_rights INTEGER NOT NULL DEFAULT 0,
    inviter_user_id BIGINT NOT NULL DEFAULT 0,
    invited_at BIGINT NOT NULL DEFAULT 0,
    kicked_at BIGINT NOT NULL DEFAULT 0,
    left_at BIGINT NOT NULL DEFAULT 0,
    groupcall_default_join_as_peer_type INTEGER NOT NULL DEFAULT 0,
    groupcall_default_join_as_peer_id BIGINT NOT NULL DEFAULT 0,
    is_bot BOOLEAN NOT NULL DEFAULT FALSE,
    state INTEGER NOT NULL DEFAULT 0,
    date2 BIGINT NOT NULL DEFAULT 0,
    rank2 TEXT NOT NULL DEFAULT '',
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT chat_participants_chat_user_key UNIQUE (chat_id, user_id)
);

CREATE INDEX IF NOT EXISTS chat_participants_user_state_idx
    ON chat_participants (user_id, state, chat_id);
CREATE INDEX IF NOT EXISTS chat_participants_chat_state_idx
    ON chat_participants (chat_id, state, user_id);

CREATE TABLE IF NOT EXISTS chat_invites (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    chat_id BIGINT NOT NULL,
    admin_id BIGINT NOT NULL,
    migrated_to_id BIGINT NOT NULL DEFAULT 0,
    link TEXT NOT NULL,
    permanent BOOLEAN NOT NULL DEFAULT FALSE,
    revoked BOOLEAN NOT NULL DEFAULT FALSE,
    request_needed BOOLEAN NOT NULL DEFAULT FALSE,
    start_date BIGINT NOT NULL DEFAULT 0,
    expire_date BIGINT NOT NULL DEFAULT 0,
    usage_limit INTEGER NOT NULL DEFAULT 0,
    usage2 INTEGER NOT NULL DEFAULT 0,
    requested INTEGER NOT NULL DEFAULT 0,
    title TEXT NOT NULL DEFAULT '',
    date2 BIGINT NOT NULL DEFAULT 0,
    state INTEGER NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT chat_invites_link_key UNIQUE (link)
);

CREATE INDEX IF NOT EXISTS chat_invites_chat_admin_idx
    ON chat_invites (chat_id, admin_id, id);
CREATE INDEX IF NOT EXISTS chat_invites_chat_revoked_idx
    ON chat_invites (chat_id, admin_id) WHERE revoked = TRUE;

CREATE TABLE IF NOT EXISTS chat_invite_participants (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    chat_id BIGINT NOT NULL DEFAULT 0,
    link TEXT NOT NULL,
    user_id BIGINT NOT NULL,
    requested BOOLEAN NOT NULL DEFAULT FALSE,
    approved_by BIGINT NOT NULL DEFAULT 0,
    date2 BIGINT NOT NULL DEFAULT 0,
    deleted BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT chat_invite_participants_link_user_key UNIQUE (link, user_id)
);

CREATE INDEX IF NOT EXISTS chat_invite_participants_link_requested_idx
    ON chat_invite_participants (link, requested, id);
CREATE INDEX IF NOT EXISTS chat_invite_participants_chat_requested_idx
    ON chat_invite_participants (chat_id, requested, date2 DESC);

CREATE OR REPLACE FUNCTION biz_chat_set_updated_at()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
    NEW.updated_at = CURRENT_TIMESTAMP;
    RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS chats_set_updated_at ON chats;
CREATE TRIGGER chats_set_updated_at
    BEFORE UPDATE ON chats
    FOR EACH ROW EXECUTE FUNCTION biz_chat_set_updated_at();

DROP TRIGGER IF EXISTS chat_participants_set_updated_at ON chat_participants;
CREATE TRIGGER chat_participants_set_updated_at
    BEFORE UPDATE ON chat_participants
    FOR EACH ROW EXECUTE FUNCTION biz_chat_set_updated_at();

DROP TRIGGER IF EXISTS chat_invites_set_updated_at ON chat_invites;
CREATE TRIGGER chat_invites_set_updated_at
    BEFORE UPDATE ON chat_invites
    FOR EACH ROW EXECUTE FUNCTION biz_chat_set_updated_at();

DROP TRIGGER IF EXISTS chat_invite_participants_set_updated_at ON chat_invite_participants;
CREATE TRIGGER chat_invite_participants_set_updated_at
    BEFORE UPDATE ON chat_invite_participants
    FOR EACH ROW EXECUTE FUNCTION biz_chat_set_updated_at();
