-- PostgreSQL 18 schema for the user and contact aggregates.
-- This is a fresh-install schema; no MySQL data compatibility is required.

CREATE TABLE IF NOT EXISTS users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_type INTEGER NOT NULL DEFAULT 2,
    access_hash BIGINT NOT NULL DEFAULT 0,
    secret_key_id BIGINT NOT NULL DEFAULT 0,
    first_name TEXT NOT NULL DEFAULT '',
    last_name TEXT NOT NULL DEFAULT '',
    username TEXT NOT NULL DEFAULT '',
    phone TEXT NOT NULL,
    country_code TEXT NOT NULL DEFAULT '',
    verified BOOLEAN NOT NULL DEFAULT FALSE,
    support BOOLEAN NOT NULL DEFAULT FALSE,
    scam BOOLEAN NOT NULL DEFAULT FALSE,
    fake BOOLEAN NOT NULL DEFAULT FALSE,
    premium BOOLEAN NOT NULL DEFAULT FALSE,
    premium_expire_date BIGINT NOT NULL DEFAULT 0,
    about TEXT NOT NULL DEFAULT '',
    state INTEGER NOT NULL DEFAULT 0,
    is_bot BOOLEAN NOT NULL DEFAULT FALSE,
    account_days_ttl INTEGER NOT NULL DEFAULT 180,
    photo_id BIGINT NOT NULL DEFAULT 0,
    restricted BOOLEAN NOT NULL DEFAULT FALSE,
    restriction_reason TEXT NOT NULL DEFAULT '',
    archive_and_mute_new_noncontact_peers BOOLEAN NOT NULL DEFAULT FALSE,
    emoji_status_document_id BIGINT NOT NULL DEFAULT 0,
    emoji_status_until INTEGER NOT NULL DEFAULT 0,
    stories_max_id INTEGER NOT NULL DEFAULT 0,
    color INTEGER NOT NULL DEFAULT 0,
    color_background_emoji_id BIGINT NOT NULL DEFAULT 0,
    profile_color INTEGER NOT NULL DEFAULT 0,
    profile_color_background_emoji_id BIGINT NOT NULL DEFAULT 0,
    birthday TEXT NOT NULL DEFAULT '',
    personal_channel_id BIGINT NOT NULL DEFAULT 0,
    authorization_ttl_days INTEGER NOT NULL DEFAULT 0,
    saved_music_id BIGINT NOT NULL DEFAULT 0,
    main_tab INTEGER NOT NULL DEFAULT 0,
    deleted BOOLEAN NOT NULL DEFAULT FALSE,
    delete_reason TEXT NOT NULL DEFAULT '',
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT users_phone_key UNIQUE (phone)
);

CREATE INDEX IF NOT EXISTS users_username_idx ON users (username text_pattern_ops) WHERE deleted = FALSE;
CREATE INDEX IF NOT EXISTS users_name_search_idx ON users (first_name text_pattern_ops, last_name text_pattern_ops) WHERE deleted = FALSE;

CREATE TABLE IF NOT EXISTS username (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username TEXT NOT NULL,
    peer_type INTEGER NOT NULL DEFAULT 0,
    peer_id BIGINT NOT NULL DEFAULT 0,
    editable BOOLEAN NOT NULL DEFAULT FALSE,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    order2 BIGINT NOT NULL DEFAULT 0,
    deleted BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE UNIQUE INDEX IF NOT EXISTS username_active_key ON username (lower(username)) WHERE deleted = FALSE;
CREATE INDEX IF NOT EXISTS username_peer_idx ON username (peer_type, peer_id, editable) WHERE deleted = FALSE;

CREATE TABLE IF NOT EXISTS user_contacts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    owner_user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    contact_user_id BIGINT NOT NULL DEFAULT 0,
    contact_phone TEXT NOT NULL DEFAULT '',
    contact_first_name TEXT NOT NULL DEFAULT '',
    contact_last_name TEXT NOT NULL DEFAULT '',
    mutual BOOLEAN NOT NULL DEFAULT FALSE,
    close_friend BOOLEAN NOT NULL DEFAULT FALSE,
    stories_hidden BOOLEAN NOT NULL DEFAULT FALSE,
    date2 BIGINT NOT NULL DEFAULT 0,
    is_deleted BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT user_contacts_owner_contact_key UNIQUE (owner_user_id, contact_user_id)
);
CREATE INDEX IF NOT EXISTS user_contacts_owner_idx ON user_contacts (owner_user_id, is_deleted, contact_user_id);
CREATE INDEX IF NOT EXISTS user_contacts_reverse_idx ON user_contacts (contact_user_id, is_deleted, owner_user_id);
CREATE INDEX IF NOT EXISTS user_contacts_phone_idx ON user_contacts (owner_user_id, contact_phone) WHERE is_deleted = FALSE;

CREATE TABLE IF NOT EXISTS user_privacies (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    key_type INTEGER NOT NULL,
    rules TEXT NOT NULL DEFAULT '',
    CONSTRAINT user_privacies_user_key UNIQUE (user_id, key_type)
);
CREATE INDEX IF NOT EXISTS user_privacies_user_idx ON user_privacies (user_id, key_type);

CREATE TABLE IF NOT EXISTS user_presences (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    last_seen_at BIGINT NOT NULL DEFAULT 0,
    expires INTEGER NOT NULL DEFAULT 0,
    CONSTRAINT user_presences_user_key UNIQUE (user_id)
);

CREATE TABLE IF NOT EXISTS user_peer_blocks (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    peer_type INTEGER NOT NULL,
    peer_id BIGINT NOT NULL,
    date BIGINT NOT NULL DEFAULT 0,
    deleted BOOLEAN NOT NULL DEFAULT FALSE,
    CONSTRAINT user_peer_blocks_peer_key UNIQUE (user_id, peer_type, peer_id)
);
CREATE INDEX IF NOT EXISTS user_peer_blocks_user_idx ON user_peer_blocks (user_id, deleted, id);

CREATE TABLE IF NOT EXISTS user_peer_settings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    peer_type INTEGER NOT NULL,
    peer_id BIGINT NOT NULL,
    hide BOOLEAN NOT NULL DEFAULT FALSE,
    report_spam BOOLEAN NOT NULL DEFAULT FALSE,
    add_contact BOOLEAN NOT NULL DEFAULT FALSE,
    block_contact BOOLEAN NOT NULL DEFAULT FALSE,
    share_contact BOOLEAN NOT NULL DEFAULT FALSE,
    need_contacts_exception BOOLEAN NOT NULL DEFAULT FALSE,
    report_geo BOOLEAN NOT NULL DEFAULT FALSE,
    autoarchived BOOLEAN NOT NULL DEFAULT FALSE,
    invite_members BOOLEAN NOT NULL DEFAULT FALSE,
    geo_distance INTEGER NOT NULL DEFAULT 0,
    CONSTRAINT user_peer_settings_peer_key UNIQUE (user_id, peer_type, peer_id)
);

CREATE TABLE IF NOT EXISTS user_notify_settings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    peer_type INTEGER NOT NULL,
    peer_id BIGINT NOT NULL,
    show_previews INTEGER NOT NULL DEFAULT 0,
    silent INTEGER NOT NULL DEFAULT 0,
    mute_until INTEGER NOT NULL DEFAULT 0,
    sound TEXT NOT NULL DEFAULT '',
    deleted BOOLEAN NOT NULL DEFAULT FALSE,
    CONSTRAINT user_notify_settings_peer_key UNIQUE (user_id, peer_type, peer_id)
);
CREATE INDEX IF NOT EXISTS user_notify_settings_user_idx ON user_notify_settings (user_id, deleted, peer_type, peer_id);

CREATE TABLE IF NOT EXISTS user_global_privacy_settings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    archive_and_mute_new_noncontact_peers BOOLEAN NOT NULL DEFAULT FALSE,
    keep_archived_unmuted BOOLEAN NOT NULL DEFAULT FALSE,
    keep_archived_folders BOOLEAN NOT NULL DEFAULT FALSE,
    hide_read_marks BOOLEAN NOT NULL DEFAULT FALSE,
    new_noncontact_peers_require_premium BOOLEAN NOT NULL DEFAULT FALSE,
    display_gifts_button BOOLEAN NOT NULL DEFAULT FALSE,
    noncontact_peers_paid_stars BIGINT,
    disallowed_gifts TEXT,
    CONSTRAINT user_global_privacy_user_key UNIQUE (user_id)
);

CREATE TABLE IF NOT EXISTS user_profile_photos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    photo_id BIGINT NOT NULL,
    date2 BIGINT NOT NULL DEFAULT 0,
    deleted BOOLEAN NOT NULL DEFAULT FALSE,
    CONSTRAINT user_profile_photos_user_photo_key UNIQUE (user_id, photo_id)
);
CREATE INDEX IF NOT EXISTS user_profile_photos_user_idx ON user_profile_photos (user_id, deleted, id);

CREATE TABLE IF NOT EXISTS user_saved_music (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    saved_music_id BIGINT NOT NULL,
    order2 BIGINT NOT NULL DEFAULT 0,
    deleted BOOLEAN NOT NULL DEFAULT FALSE,
    CONSTRAINT user_saved_music_user_music_key UNIQUE (user_id, saved_music_id)
);
CREATE INDEX IF NOT EXISTS user_saved_music_user_idx ON user_saved_music (user_id, deleted, order2, id);

CREATE TABLE IF NOT EXISTS user_settings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    key2 TEXT NOT NULL,
    value TEXT NOT NULL DEFAULT '',
    deleted BOOLEAN NOT NULL DEFAULT FALSE,
    CONSTRAINT user_settings_user_key UNIQUE (user_id, key2)
);

CREATE TABLE IF NOT EXISTS bots (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    bot_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    bot_type INTEGER NOT NULL DEFAULT 0,
    creator_user_id BIGINT NOT NULL DEFAULT 0,
    manager_bot_id BIGINT NOT NULL DEFAULT 0,
    bot_can_manage_bots BOOLEAN NOT NULL DEFAULT FALSE,
    token TEXT NOT NULL DEFAULT '',
    description TEXT NOT NULL DEFAULT '',
    bot_chat_history BOOLEAN NOT NULL DEFAULT FALSE,
    bot_nochats BOOLEAN NOT NULL DEFAULT FALSE,
    verified BOOLEAN NOT NULL DEFAULT FALSE,
    bot_inline_geo BOOLEAN NOT NULL DEFAULT FALSE,
    bot_info_version INTEGER NOT NULL DEFAULT 0,
    bot_inline_placeholder TEXT NOT NULL DEFAULT '',
    bot_attach_menu BOOLEAN NOT NULL DEFAULT FALSE,
    attach_menu_enabled BOOLEAN NOT NULL DEFAULT FALSE,
    bot_business BOOLEAN NOT NULL DEFAULT FALSE,
    bot_has_main_app BOOLEAN NOT NULL DEFAULT FALSE,
    bot_active_users INTEGER NOT NULL DEFAULT 0,
    has_menu_button BOOLEAN NOT NULL DEFAULT FALSE,
    menu_button_text TEXT NOT NULL DEFAULT '',
    menu_button_url TEXT NOT NULL DEFAULT '',
    bot_can_edit BOOLEAN NOT NULL DEFAULT FALSE,
    has_preview_medias BOOLEAN NOT NULL DEFAULT FALSE,
    description_photo_id BIGINT NOT NULL DEFAULT 0,
    description_document_id BIGINT NOT NULL DEFAULT 0,
    main_app_url TEXT NOT NULL DEFAULT '',
    has_app_settings BOOLEAN NOT NULL DEFAULT FALSE,
    placeholder_path TEXT NOT NULL DEFAULT '',
    background_color INTEGER NOT NULL DEFAULT 0,
    background_dark_color INTEGER NOT NULL DEFAULT 0,
    header_color INTEGER NOT NULL DEFAULT 0,
    header_dark_color INTEGER NOT NULL DEFAULT 0,
    privacy_policy_url TEXT NOT NULL DEFAULT '',
    mode INTEGER NOT NULL DEFAULT 0,
    CONSTRAINT bots_bot_key UNIQUE (bot_id),
    CONSTRAINT bots_token_key UNIQUE (token)
);
CREATE INDEX IF NOT EXISTS bots_creator_idx ON bots (creator_user_id, bot_id);

CREATE TABLE IF NOT EXISTS bot_commands (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    bot_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    command TEXT NOT NULL,
    description TEXT NOT NULL DEFAULT '',
    CONSTRAINT bot_commands_bot_command_key UNIQUE (bot_id, command)
);

CREATE TABLE IF NOT EXISTS default_history_ttl (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    period INTEGER NOT NULL DEFAULT 0,
    CONSTRAINT default_history_ttl_user_key UNIQUE (user_id)
);

CREATE TABLE IF NOT EXISTS imported_contacts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    imported_user_id BIGINT NOT NULL DEFAULT 0,
    deleted BOOLEAN NOT NULL DEFAULT FALSE,
    CONSTRAINT imported_contacts_user_contact_key UNIQUE (user_id, imported_user_id)
);

CREATE TABLE IF NOT EXISTS phone_books (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    auth_key_id BIGINT NOT NULL DEFAULT 0,
    client_id BIGINT NOT NULL DEFAULT 0,
    phone TEXT NOT NULL,
    first_name TEXT NOT NULL DEFAULT '',
    last_name TEXT NOT NULL DEFAULT '',
    CONSTRAINT phone_books_user_phone_key UNIQUE (user_id, phone)
);

CREATE TABLE IF NOT EXISTS popular_contacts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    phone TEXT NOT NULL,
    importers INTEGER NOT NULL DEFAULT 0,
    deleted BOOLEAN NOT NULL DEFAULT FALSE,
    update_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT popular_contacts_phone_key UNIQUE (phone)
);

CREATE TABLE IF NOT EXISTS predefined_users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    phone TEXT NOT NULL,
    first_name TEXT NOT NULL DEFAULT '',
    last_name TEXT NOT NULL DEFAULT '',
    username TEXT NOT NULL DEFAULT '',
    code TEXT NOT NULL DEFAULT '',
    verified BOOLEAN NOT NULL DEFAULT FALSE,
    registered_user_id BIGINT NOT NULL DEFAULT 0,
    deleted BOOLEAN NOT NULL DEFAULT FALSE,
    CONSTRAINT predefined_users_phone_key UNIQUE (phone)
);

CREATE TABLE IF NOT EXISTS unregistered_contacts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    phone TEXT NOT NULL,
    importer_user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    import_first_name TEXT NOT NULL DEFAULT '',
    import_last_name TEXT NOT NULL DEFAULT '',
    imported BOOLEAN NOT NULL DEFAULT FALSE,
    CONSTRAINT unregistered_contacts_phone_importer_key UNIQUE (phone, importer_user_id)
);
CREATE INDEX IF NOT EXISTS unregistered_contacts_phone_idx ON unregistered_contacts (phone, imported);

CREATE OR REPLACE FUNCTION biz_user_set_updated_at()
RETURNS TRIGGER LANGUAGE plpgsql AS $$
BEGIN
    NEW.updated_at = CURRENT_TIMESTAMP;
    RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS users_set_updated_at ON users;
CREATE TRIGGER users_set_updated_at BEFORE UPDATE ON users FOR EACH ROW EXECUTE FUNCTION biz_user_set_updated_at();
DROP TRIGGER IF EXISTS username_set_updated_at ON username;
CREATE TRIGGER username_set_updated_at BEFORE UPDATE ON username FOR EACH ROW EXECUTE FUNCTION biz_user_set_updated_at();
DROP TRIGGER IF EXISTS user_contacts_set_updated_at ON user_contacts;
CREATE TRIGGER user_contacts_set_updated_at BEFORE UPDATE ON user_contacts FOR EACH ROW EXECUTE FUNCTION biz_user_set_updated_at();
