-- PostgreSQL 18 schema for dialog state, folders, drafts and saved dialogs.
--
-- This is a fresh-install schema.  Dialog state is user-owned and the
-- (user_id, peer_dialog_id) keys are the idempotency boundaries used by the
-- MTProto dialog methods.

CREATE TABLE IF NOT EXISTS dialogs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    peer_type INTEGER NOT NULL DEFAULT 2,
    peer_id BIGINT NOT NULL,
    peer_dialog_id BIGINT NOT NULL,
    pinned BIGINT NOT NULL DEFAULT 0,
    top_message INTEGER NOT NULL DEFAULT 0,
    pinned_msg_id INTEGER NOT NULL DEFAULT 0,
    read_inbox_max_id INTEGER NOT NULL DEFAULT 0,
    read_outbox_max_id INTEGER NOT NULL DEFAULT 0,
    unread_count INTEGER NOT NULL DEFAULT 0,
    unread_mentions_count INTEGER NOT NULL DEFAULT 0,
    unread_reactions_count INTEGER NOT NULL DEFAULT 0,
    unread_mark BOOLEAN NOT NULL DEFAULT FALSE,
    draft_type INTEGER NOT NULL DEFAULT 0,
    draft_message_data JSONB NOT NULL DEFAULT 'null'::jsonb,
    folder_id INTEGER NOT NULL DEFAULT 0,
    folder_pinned BIGINT NOT NULL DEFAULT 0,
    has_scheduled BOOLEAN NOT NULL DEFAULT FALSE,
    ttl_period INTEGER NOT NULL DEFAULT 0,
    theme_emoticon TEXT NOT NULL DEFAULT '',
    wallpaper_id BIGINT NOT NULL DEFAULT 0,
    wallpaper_overridden BOOLEAN NOT NULL DEFAULT FALSE,
    date2 BIGINT NOT NULL DEFAULT 0,
    deleted BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT dialogs_user_peer_key UNIQUE (user_id, peer_type, peer_id),
    CONSTRAINT dialogs_user_peer_dialog_key UNIQUE (user_id, peer_dialog_id)
);

CREATE INDEX IF NOT EXISTS dialogs_user_folder_order_idx
    ON dialogs (user_id, folder_id, pinned DESC, folder_pinned DESC, date2 DESC, peer_dialog_id DESC)
    WHERE deleted = FALSE;
CREATE INDEX IF NOT EXISTS dialogs_user_unread_idx
    ON dialogs (user_id, unread_mark, unread_count)
    WHERE deleted = FALSE;
CREATE INDEX IF NOT EXISTS dialogs_peer_read_idx
    ON dialogs (peer_type, peer_id, read_inbox_max_id, user_id);

CREATE TABLE IF NOT EXISTS dialog_filters (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    dialog_filter_id INTEGER NOT NULL,
    is_chatlist BOOLEAN NOT NULL DEFAULT FALSE,
    joined_by_slug BOOLEAN NOT NULL DEFAULT FALSE,
    slug TEXT NOT NULL DEFAULT '',
    has_my_invites INTEGER NOT NULL DEFAULT 0,
    dialog_filter JSONB NOT NULL DEFAULT '{}'::jsonb,
    order_value BIGINT NOT NULL DEFAULT 0,
    from_suggested INTEGER NOT NULL DEFAULT 0,
    deleted BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT dialog_filters_user_id_key UNIQUE (user_id, dialog_filter_id)
);

CREATE UNIQUE INDEX IF NOT EXISTS dialog_filters_user_slug_key
    ON dialog_filters (user_id, slug)
    WHERE slug <> '' AND deleted = FALSE;
CREATE INDEX IF NOT EXISTS dialog_filters_user_order_idx
    ON dialog_filters (user_id, order_value DESC, dialog_filter_id)
    WHERE deleted = FALSE;

CREATE TABLE IF NOT EXISTS drafts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    peer_dialog_id BIGINT NOT NULL,
    draft_type INTEGER NOT NULL DEFAULT 0,
    draft_message_data JSONB NOT NULL DEFAULT 'null'::jsonb,
    date2 BIGINT NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT drafts_user_peer_dialog_key UNIQUE (user_id, peer_dialog_id)
);

CREATE INDEX IF NOT EXISTS drafts_user_idx ON drafts (user_id, peer_dialog_id);

CREATE TABLE IF NOT EXISTS saved_dialogs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    peer_type INTEGER NOT NULL,
    peer_id BIGINT NOT NULL,
    pinned BIGINT NOT NULL DEFAULT 0,
    top_message INTEGER NOT NULL DEFAULT 0,
    read_max_id INTEGER NOT NULL DEFAULT 0,
    deleted BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT saved_dialogs_user_peer_key UNIQUE (user_id, peer_type, peer_id)
);

CREATE INDEX IF NOT EXISTS saved_dialogs_user_order_idx
    ON saved_dialogs (user_id, pinned DESC, top_message DESC)
    WHERE deleted = FALSE;

CREATE TABLE IF NOT EXISTS dialog_filter_tags (
    user_id BIGINT PRIMARY KEY,
    enabled BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE OR REPLACE FUNCTION biz_dialog_set_updated_at()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
    NEW.updated_at = CURRENT_TIMESTAMP;
    RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS dialogs_set_updated_at ON dialogs;
CREATE TRIGGER dialogs_set_updated_at
    BEFORE UPDATE ON dialogs
    FOR EACH ROW EXECUTE FUNCTION biz_dialog_set_updated_at();

DROP TRIGGER IF EXISTS dialog_filters_set_updated_at ON dialog_filters;
CREATE TRIGGER dialog_filters_set_updated_at
    BEFORE UPDATE ON dialog_filters
    FOR EACH ROW EXECUTE FUNCTION biz_dialog_set_updated_at();

DROP TRIGGER IF EXISTS drafts_set_updated_at ON drafts;
CREATE TRIGGER drafts_set_updated_at
    BEFORE UPDATE ON drafts
    FOR EACH ROW EXECUTE FUNCTION biz_dialog_set_updated_at();

DROP TRIGGER IF EXISTS saved_dialogs_set_updated_at ON saved_dialogs;
CREATE TRIGGER saved_dialogs_set_updated_at
    BEFORE UPDATE ON saved_dialogs
    FOR EACH ROW EXECUTE FUNCTION biz_dialog_set_updated_at();

DROP TRIGGER IF EXISTS dialog_filter_tags_set_updated_at ON dialog_filter_tags;
CREATE TRIGGER dialog_filter_tags_set_updated_at
    BEFORE UPDATE ON dialog_filter_tags
    FOR EACH ROW EXECUTE FUNCTION biz_dialog_set_updated_at();
