-- PostgreSQL 18 schema for Telegram update difference state.
-- Each sequence key is unique so retries cannot create duplicate pts/seq events.

CREATE TABLE IF NOT EXISTS user_pts_updates (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    pts INTEGER NOT NULL,
    pts_count INTEGER NOT NULL,
    update_type INTEGER NOT NULL,
    update_data TEXT NOT NULL,
    date2 BIGINT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT user_pts_updates_user_pts_key UNIQUE (user_id, pts)
);

CREATE INDEX IF NOT EXISTS user_pts_updates_lookup_idx
    ON user_pts_updates (user_id, pts ASC);

CREATE TABLE IF NOT EXISTS auth_seq_updates (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    auth_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    seq INTEGER NOT NULL,
    update_type INTEGER NOT NULL,
    update_data TEXT NOT NULL,
    date2 BIGINT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT auth_seq_updates_auth_user_seq_key UNIQUE (auth_id, user_id, seq)
);

CREATE INDEX IF NOT EXISTS auth_seq_updates_lookup_idx
    ON auth_seq_updates (auth_id, user_id, seq ASC);
CREATE INDEX IF NOT EXISTS auth_seq_updates_date_idx
    ON auth_seq_updates (auth_id, user_id, date2 ASC, seq ASC);
