-- PostgreSQL 18 schema for the message aggregate.
-- Fresh installs use one logical table; PostgreSQL indexes provide the access
-- paths that were previously spread over MySQL shards.

CREATE TABLE IF NOT EXISTS messages (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    user_message_box_id INTEGER NOT NULL,
    dialog_id1 BIGINT NOT NULL DEFAULT 0,
    dialog_id2 BIGINT NOT NULL DEFAULT 0,
    dialog_message_id BIGINT NOT NULL DEFAULT 0,
    sender_user_id BIGINT NOT NULL,
    peer_type INTEGER NOT NULL DEFAULT 0,
    peer_id BIGINT NOT NULL DEFAULT 0,
    random_id BIGINT NOT NULL DEFAULT 0,
    message_filter_type INTEGER NOT NULL DEFAULT 0,
    message_data TEXT NOT NULL DEFAULT '',
    message TEXT NOT NULL DEFAULT '',
    mentioned BOOLEAN NOT NULL DEFAULT FALSE,
    media_unread BOOLEAN NOT NULL DEFAULT FALSE,
    pinned BOOLEAN NOT NULL DEFAULT FALSE,
    has_reaction BOOLEAN NOT NULL DEFAULT FALSE,
    reaction TEXT NOT NULL DEFAULT '',
    reaction_date BIGINT NOT NULL DEFAULT 0,
    reaction_unread BOOLEAN NOT NULL DEFAULT FALSE,
    date2 BIGINT NOT NULL DEFAULT 0,
    ttl_period INTEGER NOT NULL DEFAULT 0,
    saved_peer_type INTEGER NOT NULL DEFAULT 0,
    saved_peer_id BIGINT NOT NULL DEFAULT 0,
    outbox_read_date BIGINT NOT NULL DEFAULT 0,
    deleted BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT messages_user_box_key UNIQUE (user_id, user_message_box_id)
);

CREATE UNIQUE INDEX IF NOT EXISTS messages_sender_random_key
    ON messages (sender_user_id, random_id)
    WHERE random_id <> 0;
CREATE INDEX IF NOT EXISTS messages_dialog_order_idx
    ON messages (user_id, dialog_id1, dialog_id2, user_message_box_id DESC)
    WHERE deleted = FALSE;
CREATE INDEX IF NOT EXISTS messages_dialog_date_idx
    ON messages (user_id, dialog_id1, dialog_id2, date2 DESC, user_message_box_id DESC)
    WHERE deleted = FALSE;
CREATE INDEX IF NOT EXISTS messages_dialog_media_idx
    ON messages (user_id, dialog_id1, dialog_id2, message_filter_type, user_message_box_id DESC)
    WHERE deleted = FALSE;
CREATE INDEX IF NOT EXISTS messages_saved_order_idx
    ON messages (user_id, saved_peer_type, saved_peer_id, user_message_box_id DESC)
    WHERE deleted = FALSE;
CREATE INDEX IF NOT EXISTS messages_random_lookup_idx
    ON messages (sender_user_id, random_id)
    WHERE random_id <> 0 AND deleted = FALSE;

CREATE TABLE IF NOT EXISTS message_read_outbox (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    peer_dialog_id BIGINT NOT NULL,
    read_user_id BIGINT NOT NULL,
    read_outbox_max_id INTEGER NOT NULL DEFAULT 0,
    read_outbox_max_date BIGINT NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT message_read_outbox_user_peer_reader_key UNIQUE (user_id, peer_dialog_id, read_user_id)
);
CREATE INDEX IF NOT EXISTS message_read_outbox_lookup_idx
    ON message_read_outbox (user_id, read_user_id, read_outbox_max_id);

CREATE TABLE IF NOT EXISTS hash_tags (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    peer_type INTEGER NOT NULL,
    peer_id BIGINT NOT NULL,
    hash_tag TEXT NOT NULL,
    hash_tag_message_id INTEGER NOT NULL,
    deleted BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT hash_tags_user_peer_tag_message_key UNIQUE (user_id, peer_type, peer_id, hash_tag, hash_tag_message_id)
);
CREATE INDEX IF NOT EXISTS hash_tags_lookup_idx
    ON hash_tags (user_id, peer_type, peer_id, hash_tag)
    WHERE deleted = FALSE;

CREATE OR REPLACE FUNCTION biz_message_set_updated_at()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
    NEW.updated_at = CURRENT_TIMESTAMP;
    RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS messages_set_updated_at ON messages;
CREATE TRIGGER messages_set_updated_at BEFORE UPDATE ON messages
FOR EACH ROW EXECUTE FUNCTION biz_message_set_updated_at();
DROP TRIGGER IF EXISTS message_read_outbox_set_updated_at ON message_read_outbox;
CREATE TRIGGER message_read_outbox_set_updated_at BEFORE UPDATE ON message_read_outbox
FOR EACH ROW EXECUTE FUNCTION biz_message_set_updated_at();
DROP TRIGGER IF EXISTS hash_tags_set_updated_at ON hash_tags;
CREATE TRIGGER hash_tags_set_updated_at BEFORE UPDATE ON hash_tags
FOR EACH ROW EXECUTE FUNCTION biz_message_set_updated_at();
