-- PostgreSQL 18 schema for the media aggregate.
-- The columns mirror the current generated media data objects after the
-- historical MySQL photo-size migration (cached_type/cached_bytes).

CREATE TABLE IF NOT EXISTS documents (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    document_id BIGINT NOT NULL,
    access_hash BIGINT NOT NULL,
    dc_id INTEGER NOT NULL,
    file_path TEXT NOT NULL,
    file_size BIGINT NOT NULL DEFAULT 0,
    uploaded_file_name TEXT NOT NULL DEFAULT '',
    ext TEXT NOT NULL DEFAULT '',
    mime_type TEXT NOT NULL DEFAULT '',
    sha256 BYTEA NOT NULL DEFAULT ''::bytea,
    thumb_id BIGINT NOT NULL DEFAULT 0,
    video_thumb_id BIGINT NOT NULL DEFAULT 0,
    version INTEGER NOT NULL DEFAULT 0,
    attributes JSONB NOT NULL DEFAULT '{}'::jsonb,
    date2 BIGINT NOT NULL DEFAULT 0,
    import_document_id BIGINT NOT NULL DEFAULT 0,
    deleted BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT documents_document_id_key UNIQUE (document_id)
);
CREATE INDEX IF NOT EXISTS documents_import_document_idx
    ON documents (import_document_id) WHERE import_document_id <> 0;
CREATE INDEX IF NOT EXISTS documents_sha256_lookup_idx
    ON documents (sha256, file_size, mime_type, id)
    WHERE deleted = FALSE AND octet_length(sha256) = 32;

CREATE TABLE IF NOT EXISTS photos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    photo_id BIGINT NOT NULL,
    access_hash BIGINT NOT NULL,
    has_stickers BOOLEAN NOT NULL DEFAULT FALSE,
    dc_id INTEGER NOT NULL DEFAULT 2,
    date2 BIGINT NOT NULL DEFAULT 0,
    has_video BOOLEAN NOT NULL DEFAULT FALSE,
    size_id BIGINT NOT NULL DEFAULT 0,
    video_size_id BIGINT NOT NULL DEFAULT 0,
    input_file_name TEXT NOT NULL DEFAULT '',
    ext TEXT NOT NULL DEFAULT '',
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT photos_photo_id_key UNIQUE (photo_id)
);

CREATE TABLE IF NOT EXISTS photo_sizes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    photo_size_id BIGINT NOT NULL,
    size_type CHAR(1) NOT NULL DEFAULT '',
    width INTEGER NOT NULL DEFAULT 0,
    height INTEGER NOT NULL DEFAULT 0,
    file_size INTEGER NOT NULL DEFAULT 0,
    file_path TEXT NOT NULL DEFAULT '',
    cached_type INTEGER NOT NULL DEFAULT 0,
    cached_bytes TEXT NOT NULL DEFAULT '',
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS photo_sizes_photo_size_idx
    ON photo_sizes (photo_size_id, id);

CREATE TABLE IF NOT EXISTS video_sizes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    video_size_id BIGINT NOT NULL,
    size_type CHAR(1) NOT NULL DEFAULT '',
    width INTEGER NOT NULL DEFAULT 0,
    height INTEGER NOT NULL DEFAULT 0,
    file_size INTEGER NOT NULL DEFAULT 0,
    video_start_ts DOUBLE PRECISION NOT NULL DEFAULT 0,
    file_path TEXT NOT NULL DEFAULT '',
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS video_sizes_video_size_idx
    ON video_sizes (video_size_id, id);

CREATE OR REPLACE FUNCTION media_set_updated_at()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
    NEW.updated_at = CURRENT_TIMESTAMP;
    RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS documents_set_updated_at ON documents;
CREATE TRIGGER documents_set_updated_at BEFORE UPDATE ON documents
FOR EACH ROW EXECUTE FUNCTION media_set_updated_at();
