-- PostgreSQL 18 schema for secret-chat update state and delivery.
--
-- Secret updates are read with a repeatable-read snapshot. Keep qts unique per
-- recipient so a retry cannot expose the same update twice.

CREATE TABLE IF NOT EXISTS apifull_secret_user_state (
    user_id BIGINT PRIMARY KEY,
    last_qts INTEGER NOT NULL DEFAULT 0,
    confirmed_qts INTEGER NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS apifull_secret_message (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    chat_id INTEGER NOT NULL,
    sender_user_id BIGINT NOT NULL,
    recipient_user_id BIGINT NOT NULL,
    random_id BIGINT NOT NULL,
    qts INTEGER NOT NULL,
    date INTEGER NOT NULL,
    encrypted_data BYTEA NOT NULL,
    service BOOLEAN NOT NULL DEFAULT FALSE,
    file_id BIGINT,
    file_access_hash BIGINT,
    file_size BIGINT,
    file_dc_id INTEGER,
    file_key_fingerprint INTEGER,
    acknowledged_at INTEGER NOT NULL DEFAULT 0,
    read_at INTEGER NOT NULL DEFAULT 0,
    CONSTRAINT apifull_secret_message_sender_random_key
        UNIQUE (sender_user_id, random_id),
    CONSTRAINT apifull_secret_message_recipient_qts_key
        UNIQUE (recipient_user_id, qts)
);

CREATE INDEX IF NOT EXISTS idx_apifull_secret_message_chat
    ON apifull_secret_message (chat_id);

CREATE INDEX IF NOT EXISTS idx_apifull_secret_message_recipient
    ON apifull_secret_message (recipient_user_id, acknowledged_at);
