-- APIFull PostgreSQL 18 schema.
-- Generated from app/bff/apifull/internal/domain/domain.go canonical schema.
-- Fresh deployments use this migration; every statement is idempotent.

-- 01. apifull_channel
CREATE TABLE IF NOT EXISTS apifull_channel (
			id BIGINT NOT NULL PRIMARY KEY,
			access_hash BIGINT NOT NULL,
			migrated_from_chat_id BIGINT NULL,
			creator_user_id BIGINT NOT NULL,
			title VARCHAR(255) NOT NULL,
			about VARCHAR(1024) NOT NULL DEFAULT '',
			broadcast SMALLINT NOT NULL DEFAULT 0,
			megagroup SMALLINT NOT NULL DEFAULT 0,
			signatures_enabled SMALLINT NOT NULL DEFAULT 0,
			signature_profiles_enabled SMALLINT NOT NULL DEFAULT 0,
			antispam SMALLINT NOT NULL DEFAULT 0,
			hidden_prehistory SMALLINT NOT NULL DEFAULT 0,
			participants_hidden SMALLINT NOT NULL DEFAULT 0,
			slowmode_seconds INT NOT NULL DEFAULT 0,
			color INT NULL,
			background_emoji_id BIGINT NULL,
			profile_color INT NULL,
			profile_background_emoji_id BIGINT NULL,
			emoji_status_document_id BIGINT NOT NULL DEFAULT 0,
			emoji_status_until INT NOT NULL DEFAULT 0,
			photo_id BIGINT NOT NULL DEFAULT 0,
			photo_dc_id INT NOT NULL DEFAULT 0,
			photo_has_video SMALLINT NOT NULL DEFAULT 0,
			location_lat DOUBLE PRECISION NULL,
			location_long DOUBLE PRECISION NULL,
			location_address VARCHAR(255) NOT NULL DEFAULT '',
			username VARCHAR(64) NOT NULL DEFAULT '',
			discussion_group_id BIGINT NULL,
			created_at INT NOT NULL,

			CONSTRAINT uniq_apifull_channel_migrated_chat UNIQUE (migrated_from_chat_id)
		);
CREATE INDEX IF NOT EXISTS idx_apifull_channel_creator ON apifull_channel (creator_user_id);

-- 02. apifull_channel_member
CREATE TABLE IF NOT EXISTS apifull_channel_member (
			channel_id BIGINT NOT NULL,
			user_id BIGINT NOT NULL,
			invited_by_user_id BIGINT NOT NULL DEFAULT 0,
			joined_at INT NOT NULL,
			admin_rights VARCHAR(2048) NOT NULL DEFAULT '',
			admin_rank VARCHAR(64) NOT NULL DEFAULT '',
			banned_rights VARCHAR(2048) NOT NULL DEFAULT '',
			banned_by_user_id BIGINT NOT NULL DEFAULT 0,
			banned_at INT NOT NULL DEFAULT 0,
			PRIMARY KEY (channel_id, user_id)
);
CREATE INDEX IF NOT EXISTS idx_apifull_channel_member_user ON apifull_channel_member (user_id);

-- 03. apifull_channel_admin_log
CREATE TABLE IF NOT EXISTS apifull_channel_admin_log (
			id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
			channel_id BIGINT NOT NULL,
			actor_user_id BIGINT NOT NULL,
			target_user_id BIGINT NOT NULL DEFAULT 0,
			action VARCHAR(64) NOT NULL,
			prev_member TEXT NOT NULL,
			new_member TEXT NOT NULL,
			date INT NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_apifull_channel_admin_log_channel ON apifull_channel_admin_log (channel_id, id);
CREATE INDEX IF NOT EXISTS idx_apifull_channel_admin_log_action ON apifull_channel_admin_log (channel_id, action, id);

-- 04. apifull_call
CREATE TABLE IF NOT EXISTS apifull_call (
			id BIGINT NOT NULL PRIMARY KEY,
			access_hash BIGINT NOT NULL,
			admin_id BIGINT NOT NULL,
			participant_id BIGINT NOT NULL,
			state VARCHAR(32) NOT NULL,
			video SMALLINT NOT NULL DEFAULT 0,
			ga_hash BYTEA NULL,
			gb BYTEA NULL,
			ga BYTEA NULL,
			protocol TEXT NULL,
			key_fingerprint BIGINT NOT NULL DEFAULT 0,
			received_at INT NOT NULL DEFAULT 0,
			accepted_at INT NOT NULL DEFAULT 0,
			confirmed_at INT NOT NULL DEFAULT 0,
			discarded_at INT NOT NULL DEFAULT 0,
			discarded_by BIGINT NOT NULL DEFAULT 0,
			duration INT NOT NULL DEFAULT 0,
			reason VARCHAR(64) NOT NULL DEFAULT '',
			created_at INT NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_apifull_call_participant ON apifull_call (participant_id);

-- 05. apifull_call_artifact
CREATE TABLE IF NOT EXISTS apifull_call_artifact (
			id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
			call_id BIGINT NOT NULL,
			user_id BIGINT NOT NULL,
			kind VARCHAR(32) NOT NULL,
			payload BYTEA NOT NULL,
			created_at INT NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_apifull_call_artifact_call ON apifull_call_artifact (call_id, kind, id);
CREATE INDEX IF NOT EXISTS idx_apifull_call_artifact_user ON apifull_call_artifact (user_id, kind, id);

-- 06. apifull_stars
CREATE TABLE IF NOT EXISTS apifull_stars (
			user_id BIGINT NOT NULL PRIMARY KEY,
			balance BIGINT NOT NULL
		);

-- 07. apifull_star_tx
CREATE TABLE IF NOT EXISTS apifull_star_tx (
			id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
			user_id BIGINT NOT NULL,
			amount BIGINT NOT NULL,
			idem VARCHAR(191) NOT NULL,
			CONSTRAINT uniq_apifull_star_tx UNIQUE (user_id, idem)
		);

-- 08. apifull_stars_offer
CREATE TABLE IF NOT EXISTS apifull_stars_offer (
			id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
			kind VARCHAR(16) NOT NULL,
			stars BIGINT NOT NULL,
			store_product VARCHAR(191) NOT NULL DEFAULT '',
			currency VARCHAR(16) NOT NULL DEFAULT '',
			amount BIGINT NOT NULL DEFAULT 0,
			extended SMALLINT NOT NULL DEFAULT 0,
			active SMALLINT NOT NULL DEFAULT 1,
			CONSTRAINT uniq_apifull_stars_offer UNIQUE (kind, stars, store_product, currency, amount)
);
CREATE INDEX IF NOT EXISTS idx_apifull_stars_offer_active ON apifull_stars_offer (kind, active, id);

-- 09. apifull_payment_request
CREATE TABLE IF NOT EXISTS apifull_payment_request (
			id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
			user_id BIGINT NOT NULL,
			request_key VARCHAR(191) NOT NULL,
			provider VARCHAR(32) NOT NULL,
			fingerprint CHAR(64) NOT NULL,
			state VARCHAR(16) NOT NULL,
			transaction_id VARCHAR(191) NOT NULL DEFAULT '',
			currency VARCHAR(16) NOT NULL DEFAULT '',
			amount BIGINT NOT NULL DEFAULT 0,
			peer_id BIGINT NOT NULL DEFAULT 0,
			msg_id INT NOT NULL DEFAULT 0,
			error_text VARCHAR(255) NOT NULL DEFAULT '',
			created_at INT NOT NULL,
			updated_at INT NOT NULL,
			CONSTRAINT uniq_apifull_payment_request UNIQUE (user_id, request_key)
);
CREATE INDEX IF NOT EXISTS idx_apifull_payment_request_state ON apifull_payment_request (state, updated_at);
CREATE INDEX IF NOT EXISTS idx_apifull_payment_request_transaction ON apifull_payment_request (provider, transaction_id);

-- 10. apifull_payment_ledger
CREATE TABLE IF NOT EXISTS apifull_payment_ledger (
			id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
			request_id BIGINT NOT NULL,
			user_id BIGINT NOT NULL,
			state VARCHAR(16) NOT NULL,
			provider VARCHAR(32) NOT NULL,
			transaction_id VARCHAR(191) NOT NULL DEFAULT '',
			currency VARCHAR(16) NOT NULL DEFAULT '',
			amount BIGINT NOT NULL DEFAULT 0,
			receipt_hash CHAR(64) NOT NULL DEFAULT '',
			created_at INT NOT NULL,
			CONSTRAINT uniq_apifull_payment_ledger_state UNIQUE (request_id, state)
);
CREATE INDEX IF NOT EXISTS idx_apifull_payment_ledger_user ON apifull_payment_ledger (user_id, id);

-- 11. apifull_payment_receipt
CREATE TABLE IF NOT EXISTS apifull_payment_receipt (
			request_id BIGINT NOT NULL PRIMARY KEY,
			user_id BIGINT NOT NULL,
			provider VARCHAR(32) NOT NULL,
			transaction_id VARCHAR(191) NOT NULL,
			currency VARCHAR(16) NOT NULL DEFAULT '',
			amount BIGINT NOT NULL DEFAULT 0,
			peer_id BIGINT NOT NULL DEFAULT 0,
			msg_id INT NOT NULL DEFAULT 0,
			title VARCHAR(255) NOT NULL DEFAULT '',
			receipt BYTEA NOT NULL,
			created_at INT NOT NULL,
			CONSTRAINT uniq_apifull_payment_receipt_transaction UNIQUE (provider, transaction_id)
);
CREATE INDEX IF NOT EXISTS idx_apifull_payment_receipt_message ON apifull_payment_receipt (user_id, peer_id, msg_id);

-- 12. apifull_payment_entitlement_outbox
CREATE TABLE IF NOT EXISTS apifull_payment_entitlement_outbox (
			request_id BIGINT NOT NULL PRIMARY KEY,
			user_id BIGINT NOT NULL,
			provider VARCHAR(32) NOT NULL,
			transaction_id VARCHAR(191) NOT NULL,
			months SMALLINT NOT NULL,
			state VARCHAR(16) NOT NULL DEFAULT 'pending',
			attempts INT NOT NULL DEFAULT 0,
			next_attempt_at BIGINT NOT NULL,
			last_error VARCHAR(255) NOT NULL DEFAULT '',
			created_at BIGINT NOT NULL,
			updated_at BIGINT NOT NULL,
			CONSTRAINT uniq_apifull_payment_entitlement_transaction UNIQUE (provider, transaction_id)
);
CREATE INDEX IF NOT EXISTS idx_apifull_payment_entitlement_due ON apifull_payment_entitlement_outbox (state, next_attempt_at, request_id);

-- 13. apifull_report
CREATE TABLE IF NOT EXISTS apifull_report (
			id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
			actor_user_id BIGINT NOT NULL,
			kind VARCHAR(64) NOT NULL,
			target_type VARCHAR(32) NOT NULL,
			target_id BIGINT NOT NULL DEFAULT 0,
			dedupe_key CHAR(64) NOT NULL,
			payload BYTEA NOT NULL,
			state VARCHAR(16) NOT NULL DEFAULT 'pending',
			created_at INT NOT NULL,
			updated_at INT NOT NULL,
			CONSTRAINT uniq_apifull_report_dedupe UNIQUE (dedupe_key)
);
CREATE INDEX IF NOT EXISTS idx_apifull_report_actor ON apifull_report (actor_user_id, id);
CREATE INDEX IF NOT EXISTS idx_apifull_report_state ON apifull_report (state, id);
CREATE INDEX IF NOT EXISTS idx_apifull_report_target ON apifull_report (target_type, target_id, id);

-- 14. apifull_gift
CREATE TABLE IF NOT EXISTS apifull_gift (
			id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
			from_user BIGINT NOT NULL,
			to_user BIGINT NOT NULL,
			slug VARCHAR(191) NOT NULL,
			stars BIGINT NOT NULL DEFAULT 0,
			saved SMALLINT NOT NULL DEFAULT 1
);
CREATE INDEX IF NOT EXISTS idx_apifull_gift_to ON apifull_gift (to_user);

-- 15. apifull_username
CREATE TABLE IF NOT EXISTS apifull_username (
			username VARCHAR(64) NOT NULL PRIMARY KEY,
			owner_user_id BIGINT NOT NULL,
			kind VARCHAR(16) NOT NULL
		);

-- 16. apifull_group_call
CREATE TABLE IF NOT EXISTS apifull_group_call (
			id BIGINT NOT NULL PRIMARY KEY,
			access_hash BIGINT NOT NULL,
			creator_user_id BIGINT NOT NULL,
			channel_id BIGINT NOT NULL DEFAULT 0,
			title VARCHAR(255) NOT NULL DEFAULT '',
			rtmp_stream SMALLINT NOT NULL DEFAULT 0,
			conference SMALLINT NOT NULL DEFAULT 0,
			schedule_date INT NULL,
			participants TEXT NOT NULL,
			created_at INT NOT NULL
		);

-- 17. apifull_group_call_settings
CREATE TABLE IF NOT EXISTS apifull_group_call_settings (
			call_id BIGINT NOT NULL PRIMARY KEY,
			join_muted SMALLINT NOT NULL DEFAULT 0,
			messages_enabled SMALLINT NOT NULL DEFAULT 1,
			send_paid_messages_stars BIGINT NULL,
			record_active SMALLINT NOT NULL DEFAULT 0,
			record_video SMALLINT NOT NULL DEFAULT 0,
			record_title VARCHAR(255) NOT NULL DEFAULT '',
			record_video_portrait SMALLINT NOT NULL DEFAULT 0,
			scheduled_started SMALLINT NOT NULL DEFAULT 0,
			updated_at INT NOT NULL
		);

-- 18. apifull_group_call_invite
CREATE TABLE IF NOT EXISTS apifull_group_call_invite (
			call_id BIGINT NOT NULL PRIMARY KEY,
			creator_user_id BIGINT NOT NULL,
			token_hash BYTEA NOT NULL,
			can_self_unmute SMALLINT NOT NULL DEFAULT 0,
			revoked_at INT NOT NULL DEFAULT 0,
			created_at INT NOT NULL,
			CONSTRAINT uniq_apifull_group_call_invite_token UNIQUE (token_hash)
);
CREATE INDEX IF NOT EXISTS idx_apifull_group_call_invite_creator ON apifull_group_call_invite (creator_user_id);

-- 19. apifull_group_call_conference
CREATE TABLE IF NOT EXISTS apifull_group_call_conference (
			call_id BIGINT NOT NULL PRIMARY KEY,
			public_key BYTEA NOT NULL,
			block BYTEA NOT NULL,
			params TEXT NOT NULL,
			updated_at INT NOT NULL
		);

-- 20. apifull_group_call_participant
CREATE TABLE IF NOT EXISTS apifull_group_call_participant (
			call_id BIGINT NOT NULL,
			user_id BIGINT NOT NULL,
			media_source INT NULL,
			muted SMALLINT NOT NULL DEFAULT 0,
			volume INT NULL,
			raise_hand SMALLINT NOT NULL DEFAULT 0,
			video_stopped SMALLINT NOT NULL DEFAULT 0,
			video_paused SMALLINT NOT NULL DEFAULT 0,
			presentation_paused SMALLINT NOT NULL DEFAULT 0,
			presentation_active SMALLINT NOT NULL DEFAULT 0,
			presentation_params TEXT NOT NULL,
			join_params TEXT NOT NULL,
			updated_at INT NOT NULL,
			PRIMARY KEY (call_id, user_id),
			CONSTRAINT uniq_apifull_group_call_participant_source UNIQUE (call_id, media_source)
);
CREATE INDEX IF NOT EXISTS idx_apifull_group_call_participant_user ON apifull_group_call_participant (user_id);

-- 21. apifull_group_call_subscription
CREATE TABLE IF NOT EXISTS apifull_group_call_subscription (
			call_id BIGINT NOT NULL,
			user_id BIGINT NOT NULL,
			subscribed SMALLINT NOT NULL DEFAULT 0,
			updated_at INT NOT NULL,
			PRIMARY KEY (call_id, user_id)
		);

-- 22. apifull_group_call_send_as
CREATE TABLE IF NOT EXISTS apifull_group_call_send_as (
			call_id BIGINT NOT NULL,
			user_id BIGINT NOT NULL,
			send_as TEXT NOT NULL,
			updated_at INT NOT NULL,
			PRIMARY KEY (call_id, user_id)
		);

-- 23. apifull_group_call_message
CREATE TABLE IF NOT EXISTS apifull_group_call_message (
			id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
			call_id BIGINT NOT NULL,
			sender_user_id BIGINT NOT NULL,
			random_id BIGINT NOT NULL,
			message TEXT NOT NULL,
			send_as TEXT NOT NULL,
			paid_stars BIGINT NULL,
			date INT NOT NULL,
			deleted SMALLINT NOT NULL DEFAULT 0,
			CONSTRAINT uniq_apifull_group_call_message_random UNIQUE (call_id, random_id)
);
CREATE INDEX IF NOT EXISTS idx_apifull_group_call_message_call ON apifull_group_call_message (call_id, id);
CREATE INDEX IF NOT EXISTS idx_apifull_group_call_message_sender ON apifull_group_call_message (call_id, sender_user_id, id);

-- 24. apifull_channel_message
CREATE TABLE IF NOT EXISTS apifull_channel_message (
				channel_id BIGINT NOT NULL,
				message_id INT NOT NULL,
			sender_user_id BIGINT NOT NULL,
			date INT NOT NULL,
			message TEXT NOT NULL,
			edited SMALLINT NOT NULL DEFAULT 0,
			edited_at INT NOT NULL DEFAULT 0,
			reply_to_msg_id INT NOT NULL DEFAULT 0,
			reply_to_top_id INT NOT NULL DEFAULT 0,
			content_json TEXT NULL,
				PRIMARY KEY (channel_id, message_id)
			);

-- 25. apifull_channel_message_request
CREATE TABLE IF NOT EXISTS apifull_channel_message_request (
				channel_id BIGINT NOT NULL,
				sender_user_id BIGINT NOT NULL,
				random_id BIGINT NOT NULL,
				message_id INT NOT NULL,
				pts INT NOT NULL,
				request_hash BYTEA NOT NULL,
				created_at INT NOT NULL,
				PRIMARY KEY (channel_id, sender_user_id, random_id)
);
CREATE INDEX IF NOT EXISTS idx_apifull_channel_message_request_message ON apifull_channel_message_request (channel_id, message_id);

-- 26. apifull_channel_delivery_outbox
CREATE TABLE IF NOT EXISTS apifull_channel_delivery_outbox (
			id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
			channel_id BIGINT NOT NULL,
			pts_from INT NOT NULL,
			pts_to INT NOT NULL,
			sender_user_id BIGINT NOT NULL,
			exclude_auth_key_id BIGINT NOT NULL DEFAULT 0,
			state VARCHAR(16) NOT NULL DEFAULT 'pending',
			payload BYTEA NOT NULL,
			created_at BIGINT NOT NULL,
			CONSTRAINT uniq_apifull_channel_delivery_event UNIQUE (channel_id, pts_from, pts_to)
);
CREATE INDEX IF NOT EXISTS idx_apifull_channel_delivery_channel ON apifull_channel_delivery_outbox (channel_id, id);

-- 27. apifull_channel_delivery_recipient
CREATE TABLE IF NOT EXISTS apifull_channel_delivery_recipient (
			delivery_id BIGINT NOT NULL,
			user_id BIGINT NOT NULL,
			state VARCHAR(16) NOT NULL DEFAULT 'pending',
			attempts INT NOT NULL DEFAULT 0,
			next_attempt_at BIGINT NOT NULL,
			delivered_at BIGINT NOT NULL DEFAULT 0,
			last_error VARCHAR(255) NOT NULL DEFAULT '',
			PRIMARY KEY (delivery_id, user_id)
);
CREATE INDEX IF NOT EXISTS idx_apifull_channel_delivery_due ON apifull_channel_delivery_recipient (state, next_attempt_at, delivery_id);

-- 28. apifull_channel_message_hidden
CREATE TABLE IF NOT EXISTS apifull_channel_message_hidden (
			user_id BIGINT NOT NULL,
			channel_id BIGINT NOT NULL,
			message_id INT NOT NULL,
			PRIMARY KEY (user_id, channel_id, message_id)
);
CREATE INDEX IF NOT EXISTS idx_apifull_channel_hidden_message ON apifull_channel_message_hidden (channel_id, message_id);

-- 29. apifull_channel_message_seq
CREATE TABLE IF NOT EXISTS apifull_channel_message_seq (
			channel_id BIGINT NOT NULL PRIMARY KEY,
			last_message_id INT NOT NULL,
			pts INT NOT NULL
		);

-- 30. apifull_channel_event
CREATE TABLE IF NOT EXISTS apifull_channel_event (
			channel_id BIGINT NOT NULL,
			pts INT NOT NULL,
			pts_count INT NOT NULL DEFAULT 1,
			event_type VARCHAR(16) NOT NULL,
			message_ids TEXT NOT NULL,
			sender_user_id BIGINT NOT NULL DEFAULT 0,
			date INT NOT NULL DEFAULT 0,
			message TEXT NOT NULL,
			content_json TEXT NULL,
			edited_at INT NOT NULL DEFAULT 0,
			pinned SMALLINT NOT NULL DEFAULT 0,
			PRIMARY KEY (channel_id, pts)
);
CREATE INDEX IF NOT EXISTS idx_apifull_channel_event_cursor ON apifull_channel_event (channel_id, pts);

-- 31. apifull_channel_read_state
CREATE TABLE IF NOT EXISTS apifull_channel_read_state (
			user_id BIGINT NOT NULL,
			channel_id BIGINT NOT NULL,
			read_max_id INT NOT NULL DEFAULT 0,
			PRIMARY KEY (user_id, channel_id)
		);

-- 32. apifull_channel_message_content_read
CREATE TABLE IF NOT EXISTS apifull_channel_message_content_read (
			user_id BIGINT NOT NULL,
			channel_id BIGINT NOT NULL,
			message_id INT NOT NULL,
			read_at INT NOT NULL,
			PRIMARY KEY (user_id, channel_id, message_id)
);
CREATE INDEX IF NOT EXISTS idx_apifull_channel_content_read_message ON apifull_channel_message_content_read (channel_id, message_id);

-- 33. apifull_secret_chat
CREATE TABLE IF NOT EXISTS apifull_secret_chat (
			id INT NOT NULL PRIMARY KEY,
			access_hash BIGINT NOT NULL,
			admin_user_id BIGINT NOT NULL,
			participant_user_id BIGINT NOT NULL,
			state VARCHAR(16) NOT NULL,
			g_a BYTEA NOT NULL,
			g_b BYTEA NULL,
			key_fingerprint BIGINT NOT NULL DEFAULT 0,
			created_at INT NOT NULL,
			accepted_at INT NOT NULL DEFAULT 0,
			discarded_at INT NOT NULL DEFAULT 0,
			discarded_by_user_id BIGINT NOT NULL DEFAULT 0,
			history_deleted SMALLINT NOT NULL DEFAULT 0
);
CREATE INDEX IF NOT EXISTS idx_apifull_secret_chat_admin ON apifull_secret_chat (admin_user_id);
CREATE INDEX IF NOT EXISTS idx_apifull_secret_chat_participant ON apifull_secret_chat (participant_user_id);

-- 34. apifull_secret_chat_device_key
CREATE TABLE IF NOT EXISTS apifull_secret_chat_device_key (
			chat_id INT NOT NULL,
			user_id BIGINT NOT NULL,
			device_id BIGINT NOT NULL,
			epoch INT NOT NULL,
			public_key BYTEA NOT NULL,
			fingerprint BIGINT NOT NULL DEFAULT 0,
			created_at INT NOT NULL,
			PRIMARY KEY (chat_id, user_id, device_id, epoch)
);
CREATE INDEX IF NOT EXISTS idx_apifull_secret_device_key ON apifull_secret_chat_device_key (chat_id, user_id, device_id, epoch);

-- 35. apifull_secret_user_state
CREATE TABLE IF NOT EXISTS apifull_secret_user_state (
			user_id BIGINT NOT NULL PRIMARY KEY,
			last_qts INT NOT NULL DEFAULT 0,
			confirmed_qts INT NOT NULL DEFAULT 0
		);

-- 36. apifull_secret_message
CREATE TABLE IF NOT EXISTS apifull_secret_message (
			id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
			chat_id INT NOT NULL,
			sender_user_id BIGINT NOT NULL,
			recipient_user_id BIGINT NOT NULL,
			random_id BIGINT NOT NULL,
			qts INT NOT NULL,
			date INT NOT NULL,
			encrypted_data BYTEA NOT NULL,
			service SMALLINT NOT NULL DEFAULT 0,
			file_id BIGINT NULL,
			file_access_hash BIGINT NULL,
			file_size BIGINT NULL,
			file_dc_id INT NULL,
			file_key_fingerprint INT NULL,
			acknowledged_at INT NOT NULL DEFAULT 0,
			read_at INT NOT NULL DEFAULT 0,
			CONSTRAINT uniq_apifull_secret_sender_random UNIQUE (sender_user_id, random_id),
			CONSTRAINT uniq_apifull_secret_recipient_qts UNIQUE (recipient_user_id, qts)
);
CREATE INDEX IF NOT EXISTS idx_apifull_secret_message_chat ON apifull_secret_message (chat_id);
CREATE INDEX IF NOT EXISTS idx_apifull_secret_message_recipient ON apifull_secret_message (recipient_user_id, acknowledged_at);

