-- PostgreSQL 18 audit trail for the controlled bot-manager capability toggle.
CREATE TABLE IF NOT EXISTS bot_manager_capability_audit (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    bot_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    old_enabled BOOLEAN NOT NULL,
    new_enabled BOOLEAN NOT NULL,
    operator_db_user TEXT NOT NULL,
    reason TEXT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS bot_manager_capability_audit_bot_idx
    ON bot_manager_capability_audit (bot_id, id);
