-- PostgreSQL 18 durable state for Layer 229 takeout sessions and wallpapers.
-- JSONB preserves the generated TL object fields while the owning rows provide
-- transactional locking and cross-process consistency.
CREATE TABLE IF NOT EXISTS apifull_takeout_session (
    user_id BIGINT PRIMARY KEY,
    takeout_id BIGINT GENERATED BY DEFAULT AS IDENTITY UNIQUE,
    payload JSONB NOT NULL DEFAULT '{}'::jsonb,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS apifull_wallpaper_state (
    user_id BIGINT NOT NULL,
    uploaded BOOLEAN NOT NULL,
    wallpapers JSONB NOT NULL DEFAULT '[]'::jsonb,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (user_id, uploaded)
);
