-- PostgreSQL 18 forum topics and channel forum settings.
CREATE TABLE IF NOT EXISTS apifull_forum_topic (
    peer_key TEXT NOT NULL,
    topic_id INTEGER GENERATED BY DEFAULT AS IDENTITY,
    title TEXT NOT NULL,
    closed BOOLEAN NOT NULL DEFAULT FALSE,
    pinned BOOLEAN NOT NULL DEFAULT FALSE,
    hidden BOOLEAN NOT NULL DEFAULT FALSE,
    topic_date INTEGER NOT NULL DEFAULT 0,
    creator_user_id BIGINT NOT NULL,
    icon_emoji_id BIGINT NOT NULL DEFAULT 0,
    top_message INTEGER NOT NULL DEFAULT 0,
    position BIGINT NOT NULL,
    PRIMARY KEY (peer_key, topic_id)
);

CREATE INDEX IF NOT EXISTS idx_apifull_forum_topic_order
    ON apifull_forum_topic (peer_key, position, topic_id);

CREATE TABLE IF NOT EXISTS apifull_forum_user_title (
    user_id BIGINT PRIMARY KEY,
    title TEXT NOT NULL DEFAULT ''
);

CREATE TABLE IF NOT EXISTS apifull_forum_channel_settings (
    channel_id BIGINT PRIMARY KEY,
    enabled BOOLEAN NOT NULL DEFAULT FALSE,
    tabs BOOLEAN NOT NULL DEFAULT FALSE,
    view_as_messages BOOLEAN NOT NULL DEFAULT FALSE,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);
