-- Client help.saveAppLog events. The payload is JSONB so operators can query
-- event fields without coupling the retention table to the TL wire model.
CREATE TABLE IF NOT EXISTS apifull_app_log (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    event_time DOUBLE PRECISION NOT NULL,
    event_type TEXT NOT NULL,
    peer_id BIGINT NOT NULL DEFAULT 0,
    data JSONB NOT NULL DEFAULT '{}'::jsonb,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_apifull_app_log_user_time
    ON apifull_app_log (user_id, event_time DESC, id DESC);
CREATE INDEX IF NOT EXISTS idx_apifull_app_log_type_time
    ON apifull_app_log (event_type, event_time DESC, id DESC);
