-- Durable, caller-owned Stars refund state. Provider approval is kept
-- alongside the local negative ledger entry so retries cannot refund twice.
CREATE TABLE IF NOT EXISTS apifull_stars_refund (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    charge_id VARCHAR(191) NOT NULL,
    provider VARCHAR(32) NOT NULL,
    stars BIGINT NOT NULL CHECK (stars > 0),
    refund_transaction_id VARCHAR(191) NOT NULL,
    state VARCHAR(16) NOT NULL CHECK (state IN ('complete')),
    receipt BYTEA NOT NULL,
    created_at BIGINT NOT NULL,
    updated_at BIGINT NOT NULL,
    CONSTRAINT uniq_apifull_stars_refund_charge UNIQUE (user_id, charge_id),
    CONSTRAINT uniq_apifull_stars_refund_transaction UNIQUE (provider, refund_transaction_id)
);

CREATE INDEX IF NOT EXISTS idx_apifull_stars_refund_user
    ON apifull_stars_refund (user_id, id);
