-- PostgreSQL 18 authoritative metadata for encrypted files.
--
-- DFS owns the object bytes, while Media owns the identity returned at the
-- MTProto boundary. Keeping the access hash and creator here lets
-- media.getEncryptedFile reject forged locations and survive cache expiry or
-- a service restart.

CREATE TABLE IF NOT EXISTS encrypted_files (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    encrypted_file_id BIGINT NOT NULL,
    owner_id BIGINT NOT NULL,
    access_hash BIGINT NOT NULL,
    file_size BIGINT NOT NULL,
    dc_id INTEGER NOT NULL,
    key_fingerprint INTEGER NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT encrypted_files_file_id_key UNIQUE (encrypted_file_id)
);

CREATE INDEX IF NOT EXISTS encrypted_files_owner_idx
    ON encrypted_files (owner_id, encrypted_file_id);
