-- Durable opaque payloads for phone.sendGroupCallEncryptedMessage.
CREATE TABLE IF NOT EXISTS apifull_group_call_encrypted_message (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    call_id BIGINT NOT NULL,
    sender_user_id BIGINT NOT NULL,
    digest BYTEA NOT NULL,
    encrypted_message BYTEA NOT NULL,
    date INTEGER NOT NULL,
    CONSTRAINT uniq_apifull_group_call_encrypted_message
        UNIQUE (call_id, sender_user_id, digest)
);

CREATE INDEX IF NOT EXISTS idx_apifull_group_call_encrypted_message_call
    ON apifull_group_call_encrypted_message (call_id, id);
